### ISSUE TITLE
after update to 0.32.1, component event has payload type error

### ISSUE THREAD

**Issue by ysneo** [johnsoncodehk/volar#1001]
vue 2.6
volar update to 0.32.1
ts 4.5.5
I use elementui select component. it has change event ,  has payload error after volar update to 0.32.1;
`
(property) 'change': ((payload: Event) => void) | undefined
Type '(item: any[]) => Promise<void>' is not assignable to type '(payload: Event) => void'.
  Types of parameters 'item' and 'payload' are incompatible.
`
![image](https://s3.bmp.ovh/imgs/2022/03/a080c12b59fbb241.png)

**Comment by johnsoncodehk** [comment]
Could you also provide what is the old behavior in 0.32.0?

**Comment by ysneo** [comment]
I installed 0.32.0 VSIX, here is the old behavior;
![32.0](https://s3.bmp.ovh/imgs/2022/03/c8fa938dbebfb3d2.png)

**Comment by scrapstation** [comment]
+1

**Comment by barfurth** [comment]
Is there an estimate for a fix for this? It causes nearly all my components to show problems and is quite detrimental to efficient development.

**Comment by johnsoncodehk** [comment]
@barfurth please use 0.32.0 for now. I'm working on #1009 currently, this pr change all server code so I can't resolve other problem before merge it.

**Comment by johnsoncodehk** [comment]
@ysneo seems element-ui do not have valid events define in ElSelect class, it should have `$props: { onChange: (arg: ARG_TYPE) => void }` or `$emit: { (e: 'change', arg: ARG_TYPE): void }` for event type.
https://github.com/ElemeFE/element/blob/473ef53f9317ad6ca8c629655982244902751e63/types/select.d.ts#L11

If element-ui not going to support types, I recommend you to use Vetur as it built-in support intellisense for ElementUI in Vue2.

---

@NikhilVerma your component does not provide a valid type, try change it to

```vue
// Component.vue
<template>
  <div @click="selectTab">hello</div>
</template>

<script lang="ts">
import Component from "vue-class-component";

@Component
export default class Comp extends Vue {
  $emit!: { (e: 'select', value: number): any }
  selectTab() {
    this.$emit("select", 1);
  }
}
</script>
```

```vue
// Consumer.vue
<template>
  <Component @select="selectTab" />
</template>

<script lang="ts">
import Component from "vue-class-component";
import MyComponent from "./Component.vue";

@Component({
  components: {
    Component,
  },
})
export default class Consumer extends Vue {
  static components: { Component: typeof MyComponent }
  selectTab(value: number) {
    console.log(value);
  }
}
</script>
```

See https://github.com/johnsoncodehk/volar/pull/750#issuecomment-1023947885.

**Comment by barfurth** [comment]
@johnsoncodehk I’m not sure this issue is addressed considering this was working before. 

We can’t really expect every UI library to type their components? Also this would not work for dynamically registered components, because Volar wouldn’t know what to look for (e.g. Nuxt directory based imports)? Perhaps this is a separate issue.

**Comment by johnsoncodehk** [comment]
@barfurth it's changed in https://github.com/johnsoncodehk/volar/commit/99386bee9f25c73f7b13cdec2b358c6a1c09a7a7.
This issue is for invalid type components (no $props defined), so now I'm just rolling back to the previous behavior for invalid type components.

For dynamically components, see https://github.com/johnsoncodehk/volar/issues/682#issuecomment-965612541.
