### ISSUE TITLE
postcss(css-lcurlyexpected) error when using PostCSS

### ISSUE THREAD

**Issue by sto3psl** [johnsoncodehk/volar#103]
Hi there and first of all, thanks for this project!

I'm having some issues with using `<style lang="postcss">`.

I have a Vue 3 project with TailwindCSS and when using `@apply` in combination with normal CSS rules, I get an error `postcss(css-lcurlyexpected)`.

Example code:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/5798652/111438440-87a09880-8704-11eb-8878-94a157acc4de.png">

```postcss
<style lang="postcss" scoped>
.panel {
  @apply p-4 bg-neutral-50;

  min-height: var(--space-14);
}
</style>
```

This does not happen in `.css` files or in any other project. Only when using Vue 3 and Volar. Does anyone have an idea why that is happening?

Volar Version: 0.22.16
VSCode Version: 1.54.3

Some VSCode settings I have:
```json
  "volar.style.defaultLanguage": "postcss",
  "stylelint.enable": true,
  "tailwindCSS.validate": true,
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
```

It doesn't matter though If I toggle these, the error still appears.

**Comment by sto3psl** [comment]
I just installed a clean copy of VSCode with only Volar, no other extensions (not even PostCSS language support) and still get the same error.

**Comment by johnsoncodehk** [comment]
Currently postcss support is limited, postcss is recognized as loose scss, and `@apply p-4 bg-neutral-50;` broke scss ast, I will request [upstream](https://github.com/microsoft/vscode-css-languageservice) handle it because the syntax after the semicolon should not be affected.

You can use `<!-- @vue-ignore -->` for now, this will get the same result as vetur because vetur ignore all postcss diagnosis:
```vue
<!-- @vue-ignore -->
<style lang="postcss" scoped>
.panel {
  @apply p-4 bg-neutral-50;

  min-height: var(--space-14);
}
</style>
```

**Comment by sto3psl** [comment]
Thanks for the quick reply @johnsoncodehk!

Is there a way to configure `@vue-ignore` for the whole project? I'd rather not add this to every file 😅.

**Comment by johnsoncodehk** [comment]
Maybe provide an option, but I want to avoid this way, let me think about it.

btw I just found you can put `@apply` after properties to avoid for now:
```css
.panel {
  min-height: var(--space-14);

  @apply p-4 bg-neutral-50;
}
```

**Comment by sto3psl** [comment]
Yeah it does. It basically puts all the apply rules after the `min-height`, order is important (like in CSS).

```postcss
.panel {
  min-height: var(--space-14);

  @apply p-4 bg-neutral-50;
}

//compiled
.panel {
  min-height: var(--space-14);

  padding: 4px;
  background: #123;
}
```

Something like this.

Is there a way to let Volar always behave like it does with `@vue-ignore` instead of the opposite? Then users don't have to add it. When I understand it correctly that's what Vetur does (?). Are there any downsides with other languages like CSS, Less, SCSS?

---


Btw, I already added the comment to my files for now 😄

**Comment by johnsoncodehk** [comment]
> Is there a way to let Volar always behave like it does with @vue-ignore instead of the opposite?

Currently we can't, it was conflict with volar design principles. But I will improve it by some way.

> I understand it correctly that's what Vetur does

Yes.

> Are there any downsides with other languages like CSS, Less, SCSS?

`stylus`, `sass`, `postcss` works limited. But `css`, `less`, `scss` works fine because it as reliable language support by [vscode-css-languageservice](https://github.com/microsoft/vscode-css-languageservice).

`stylus`, `sass` only support auto-complete (with emmet) and syntax highlighting.
`postcss` support with `scss` language service but ignore some errors: https://github.com/johnsoncodehk/volar/blob/988fb927886d9291886e406f6ee0dcebc923c639/packages/vscode-vue-languageservice/src/utils/languageServices.ts#L15-L24

**Comment by johnsoncodehk** [comment]
I has make a temporarily patching in 0.22.21, because not sure `vscode-css-languageservice` will be fix soon.

**Comment by segevfiner** [comment]
I'm still seeing css-rcurlyexpected errors with v0.39.5 and VS Code 1.70.0. This should be reopened

**Comment by Darkzarich** [comment]
@segevfiner this extension might help https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss

**Comment by segevfiner** [comment]
Doesn't seem to help. And it is unmaintained. Maybe it isn't triggered for plain style blocks. (No `lang`)

**Comment by Darkzarich** [comment]
@segevfiner despite it being unmaintained it works for now
Volar said they won't natively support PostCSS due to technical reasons so we have the only option 
Not sure why it doesn't work for you though 
![image](https://user-images.githubusercontent.com/18618206/184829500-0eb42dba-af9c-431e-be1b-47556a693db5.png)

**Comment by segevfiner** [comment]
It seems to require `lang="postcss"` but our code base isn't using that. I wonder if Volar could integrate with the maintained postcss extension to make it work.

**Comment by johnsoncodehk** [comment]
@segevfiner I'm open with this, you can open feature request.

**Comment by tmlmt** [comment]
Has anyone managed to make it work with vscodium? I suppose it should work the same as vscode, but it doesn't work on my system.

**Comment by hriverahdez** [comment]
I also have a different use case, I'm using a [postcss mixin](https://github.com/postcss/postcss-mixins) but in the project Tailwind is not used, so I would be ok with simply having a way to ignore a single line, so that the file is not flagged red by the editor as having a problem. 

Is there a way to do this? I tried the `<!-- @vue-ignore -->` approach but that doesn't seem to do anything (I also want to know if it's possible to simply ignore that line, but not the whole style block)

**Comment by hriverahdez** [comment]
Is there still no solution to this? Again, I just want to ignore the error because it flags my SFC files as having errors.
