### ISSUE TITLE
`target: 2.7` throws error on `aria-hidden` attribute

### ISSUE THREAD

**Issue by sodatea** [johnsoncodehk/volar#1526]
Reproduction: https://stackblitz.com/edit/vitejs-vite-neriqf?file=src/App.vue
(Run `npm run build` to see the error)

Source code in `App.vue`:

```
  <button>
      <span class="fa fa-tweet" aria-hidden="true"></span>
      <span class="label"> Tweet </span>
    </button>
```

Error on type-checking:

```
src/App.vue:20:33 - error TS2322: Type '{ class: string; ariaHidden: string; "aria-hidden": "true"; }' is not assignable to type 'ElementAttrs<HTMLAttributes>'.
  Property 'ariaHidden' does not exist on type 'ElementAttrs<HTMLAttributes>'. Did you mean ''aria-hidden''?

20       <span class="fa fa-tweet" aria-hidden="true"></span>
                                   ~~~~~~~~~~~


Found 1 error in src/App.vue:20
```

**Comment by rossinek** [comment]
I experienced the same problem and even created a simple reproduction (because I did not notice this thread):
https://stackblitz.com/edit/github-5pgg1d
```
npm run tsc
```
As you may notice neither [expanding custom attrs](https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472) nor [default suppressing errors](https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1146584565) works (unless I'm doing something wrong).
