### ISSUE TITLE
Feature request: add a config to allow to choose kebab-case or PascalCase

### ISSUE THREAD

**Issue by g-plane** [johnsoncodehk/volar#156]
Some projects use kebab-case as tag names of components in template while some projects use PascalCase, however, currently Volar provides both kebab-case and PascalCase in completion list when typing.

I hope we can add a new extension config called `volar.tagNameCase`. This config has three options:

- `both` provides both kebab-case and PascalCase, which behaves as now, and this should be default value
- `kebab-case` only shows kebab-case in completion list
- `PascalCase` only shows PascalCase in completion list

**Comment by johnsoncodehk** [comment]
This is a problem, but I want to avoid create more options.

I may want to check user typing.

- When input `f`, return `foo-bar`.
- When input `F`, return `FooBar`.

**Comment by g-plane** [comment]
> I want to avoid create more options

Can you tell me the reason?

> I may want to check user typing

This sounds not good. Auto-completion should be case-insensitive; otherwise, those users who use PascalCase must use uppercased-letter to select the item, because if they type like `f...`, they won't be able to select `FooBar`, which is inconvenient and unintended.

**Comment by johnsoncodehk** [comment]
> Can you tell me the reason?

This is a UX consideration.

- If there are too many useless options, it will be more difficult for users to find the options they want.
- User will connect some options for specific project in subconscious.

This sounds not good. Auto-completion should be case-insensitive; otherwise, those users who use PascalCase must use uppercased-letter to select the item, because if they type like f..., they won't be able to select FooBar, which is inconvenient and unintended.

How about if we divided into 3 situations?

1. Not sure (input `f...`), show both
2. Determine is `kebab-case` (input include `-`), show `kebab-case`
3. Determine is `PascalCase` (input `F...`), show `PascalCase`

**Comment by g-plane** [comment]
1. 
- Code editor extensions aren't similar to something like Prettier or ESLint that enforcing something. In reverse, it should be able to be highly customized by users. (Imagine if you can't custom the theme of your editor. That will be annoying.)
- Options have default values so for those users don't want to configure too much, they can just use default values.
- VS Code allow workspace-specific configuration, even we can commit this configuration to VCS to share it with each other.

2.
- If typing `foobar` (all are lowercase), it will show both, but this has no effect on making coding efficient. This doesn't match my initial purpose.
- If typing with `-` or `F...`, users won't be able to type with keyboard fluently, because the `-` key is far from the letters area (you must move your hand, not just fingers); or hold pressing Shift key to type uppercase letter. Both are not convenient as normal lowercase letters. You can try typing something with lowercase letters only in TypeScript file, and VS Code will show everything even it contains uppercase letters.

**Comment by johnsoncodehk** [comment]
Thank you for the detailed explanation. UX is very important, more comments are welcome.

> VS Code allow workspace-specific configuration, even we can commit this configuration to VCS to share it with each other.

Modern workspaces sometimes contain multiple projects, and the only VSC setting cannot handle it well.

> If typing foobar (all are lowercase), it will show both, but this has no effect on making coding efficient. This doesn't match my initial purpose.

I agree. That was not user friendly to PascalCase use cases.

---

I think the UX/DX of `volar.tagNameCase` is not good enough, because:

- It is specific to workspace, but I think is should specific to file
- The user may often need to change this behavior, and the user needs to enter the VSC Settings to change, which is not user-friendly

I think this demand very close to VSC Indent, user can easy config indent in status bar.

<img width="596" alt="螢幕截圖 2021-04-25 上午12 03 49" src="https://user-images.githubusercontent.com/16279759/115965043-d6d6b600-a559-11eb-8605-d2ff4138f93e.png">

We can make a similar thing, the options may like:

- Component Using kebab-case
- Component Using PascalCase
- Detect Component name from Content
- Convert Component name to kebab-case
- Convert Component name to PascalCase

(Off topic: maybe also with props)

**Comment by g-plane** [comment]
- VS Code allows you to change indent in global or workspace settings, but it also allows to change by single file. However, this is one-time operation: once you close file and open the same file again, indent setting will be reset. (Yes, it can be detected.)
- I don't know how we can do with status bar, since we already have "TS Plugin" item. Adding more items on status bar will make it messy, while merge it with "TS Plugin" into one status bar item may make it hard to access and may be confusing.

**Comment by johnsoncodehk** [comment]
> I don't know how we can do with status bar, since we already have "TS Plugin" item. Adding more items on status bar will make it messy, while merge it with "TS Plugin" into one status bar item may make it hard to access and may be confusing.

Yes, we will have more status bar items, but I think this is a reasonable trade-off.

In addition, we can do something to reduce the disadvantages:

- Make `[Volar] TS Plugin` status shorter. (maybe change to VTSP)
- Only show this status bar item on vue document.
- Allow user to hide this status bar item by some way.

**Comment by iendeavor** [comment]
> Detect Component name from Content

Maybe this is good enough? 🤔 

E.g.,: We type `foo`, it will suggests `foo-bar` if current component is `kebab-case`, `FooBar` Otherwise.

**Comment by johnsoncodehk** [comment]
Supported in 0.24.2.

**Comment by kevinlys88** [comment]
> 

Thanks for working on this feature!
However I found it a little bothering since I need to config it for each vue file.
Is there a one time config from the namespace/project folder level ?

**Comment by Pryscy** [comment]
Same question for me. I read that you don't want an extension config but it's annoying when you have to have a global configuration on a whole project that you share within a development team.

**Comment by johnsoncodehk** [comment]
@kevinlys88 yes it can, see https://github.com/johnsoncodehk/volar/discussions/1714#discussioncomment-3403230
