### ISSUE TITLE
New strictTemplates option causes issues with data-* attributes

### ISSUE THREAD

**Issue by 2-5** [johnsoncodehk/volar#1561]
It seems the fix for #1413 is not complete, I'm seeing `data-*` errors with the latest Volar and `strictTemplates` on.

![data](https://user-images.githubusercontent.com/3753822/178277145-57152cd4-f796-4359-b5a4-a970402c269a.png)

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1418#issuecomment-1179656286.
You need to define `HTMLAttributes` interface to allow `data-*`, see https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1146573602.

**Comment by rchl** [comment]
A suggestion to manually add definitions for all attributes that are already valid HTML attributes doesn't really make sense to me. This applies both to `data-*` and `aria-*`.

And I suppose mine #1871 is a duplicate.

**Comment by rchl** [comment]
I understand that there might be technical difficulties with solving it but if Volar strives to be user-friendly official Vue language server then it can't require everyone to do such basic things.

We should at least keep some issue open for it so that it's clear that it's a bug (or something to solve at some point) and not make this suggestion an official response.

Maybe the solution would be for volar to include the list of known attributes (would work for aria-* at least).

**Comment by johnsoncodehk** [comment]
FYI it should handle by `dataAttributes` and `htmlAttributes` options after v1.0: https://github.com/johnsoncodehk/volar/blob/19cc0f56865fa3827420b15e85f4ab26e9850e18/vue-language-tools/vue-language-core/schemas/vue-tsconfig.schema.json#L39-L48
