### ISSUE TITLE
Add a "Volar: Reload Project" command

### ISSUE THREAD

**Issue by segevfiner** [johnsoncodehk/volar#1605]
Current limitations in ts-server file watching can often lead to a need to either restart the server or reload the project. Reloading the project can often be faster than a full restart but is not exposed in Volar unlike in the builtin TypeScript extension.

**Comment by segevfiner** [comment]
The TypeScript plugin has both a restart and reload commands are they the same underneth?

**Comment by johnsoncodehk** [comment]
It seems "TypeScript: Reload Project" is subset of "TypeScript: Restart TS server" and faster than it. 

But I'm not sure if implement "Reload Project" in Volar is meaningful if only it's just faster.

**Comment by segevfiner** [comment]
Mostly I suggested this due to ts-server still having trouble nowadays with keeping it's status up-to-date often prompting me to having to reload/restart it and in takeover mode it is Volar that takes the responsibility of running it.

**Comment by jods4** [comment]
I wonder how much is a limitation in TS itself or caused by Volar. 
@johnsoncodehk if you feel this is hijacking the wrong issue, feel free to copy-paste this report into a new issue.

In my project, we have a watcher tool that generates and updates TS files in the background, based on our server-side code. Basically, think of generating your client code to call the server web API.

This is a constant source of "Volar: Restart Vue Server" and that's super annoying and flow-breaking.

Here's an example of what happens:
0. Prerequisites: assume the project is already open and the modified client TS file *has never been opened in VS Code*.

1. For this example, I added a method `getTest` on my server, so the client TS file is updated by our tool with this addition.

2. Try to use the new method in a plain TS file: _everything works ok_.
![image](https://user-images.githubusercontent.com/3832820/180816589-7ba1d8e5-6bae-4ad7-a14c-60629d7554cb.png)

3. Now try the same in a Vue SFC: the new function is not picked up, as if TS server has not seen the changes:
![image](https://user-images.githubusercontent.com/3832820/180817067-389d0abc-8caf-4b0d-a27a-a31bbb62778d.png)

This is in the same project, same VS Code session. So it looks like plain TS is a little better than Volar at picking file changes.

**Comment by segevfiner** [comment]
TS 4.8 might include improvements to the buggy file watcher behavior BTW.

**Comment by johnsoncodehk** [comment]
@jods4 Volar doesn't implement file watch by itself, but delegates to LSP events (same as Vetur), so you should be able to reproduce the same problem in vetur.

**Comment by johnsoncodehk** [comment]
v0.39.3 "Volar: Reload Project" command cannot detect node_modules change, will fix in v0.39.4.

**Comment by jods4** [comment]
@johnsoncodehk I have not tested with Vetur, it may not work either.
The strange thing is that in a regular plain TS file, it works (see above).

So somehow the TS language server on its own seems to do fine. Volar must be doing something differently that leads to missed file changes.

If there's anything that I can provide to help to find the difference, maybe like logs, just let me know.

**Comment by johnsoncodehk** [comment]
VSCode provide language support for .ts via tsserver, tsserver implement it own file watch logic but not use LSP file watcher.

I think every LSP language extension should have same problem, you should port this problem to VSCode repo.

**Comment by segevfiner** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-8-beta/#file-watching-fixes
