### ISSUE TITLE
Syntax highlighting wrong when using valid slot names with special characters

### ISSUE THREAD

**Issue by Anoesj** [johnsoncodehk/volar#1646]
Hi, I've noticed that the syntax highlighting of slot props breaks when the slot name contains special characters like `(`/`)`/`[`/`]`/`+`. Example:

#### Table.vue (simplified)
```vue
<table v-if="data.length > 0">
  <tbody>
    <tr
      v-for="(row, index) in data"
      :key="index"
    >
      <td
        v-for="col in columns"
        :key="col.key"
        :class="{actions: col.key === 'actions'}"
      >
        <slot
          :name="`cell(${col.key})`"
          :content="row[col.key]"
          :row="row"
        >
          {{ row[col.key] }}
        </slot>
      </td>
    </tr>
  </tbody>
</table>
```

#### UserOverview.vue
```vue
<Table
  :columns="[
    { key: 'id', label: '' },
    { key: 'name', label: $t('routes.users.label_name') },
    { key: 'email', label: $t('routes.users.label_email') },
    { key: 'actions' },
  ]"
  :data="users"
>
  <template #cell(id)="{ content }">
    <Checkbox
      v-model="selected"
      :value="content"
    />
  </template>

  <template #cell(actions)="{ row }">
    <Button
      :href="route('admin.users.edit', [row.id])"
      icon="edit"
      :title="$t('global.navigation.edit')"
      :tooltip="$t('global.navigation.edit')"
    />
  </template>
</Table>
```

Now, the slot names `#cell(id)` and `#cell(actions)` are valid AFAIK, but the syntax highlighting breaks because we used a `(` and `)` in them. When removing the parentheses and using an underscore (e.g.: `#cell_id`), the problem goes away.

**Comment by johnsoncodehk** [comment]
It can resolve by replace this line:
https://github.com/johnsoncodehk/volar/blob/d0bb3da2991c3dc18af350f246e71b9211585422/extensions/vscode-vue-language-features/syntaxes/vue.tmLanguage.json#L892

to `"begin": "(?:\\b(v-)|(:)|(@)|(#))(\\[?)([\\w\\-\\(\\)]*)(\\]?)(?:\\.([\\w\\-]*))*",`.

But it brings some complexity to maintenance, and I think it can support just because this is valid HTML syntax so vue HTML parser can transform it, but it shouldn't be expected use case. If you look to vue original syntax highlight library it also don't support for `()`: https://github.com/vuejs/vue-syntax-highlight/blob/2a3e89e415f49f5fbe8bf8bf42e45f8f78ccf642/vue.tmLanguage#L1377

For the above reasons we will not support this, but if you need you can open `extension/syntaxes/vue.tmLanguage.json` in extension path and modify line 892.
