### ISSUE TITLE
Syntax highlighting of arrow => after upgrade to VS Code 1.70

### ISSUE THREAD

**Issue by 2-5** [johnsoncodehk/volar#1675]
After today's upgrade of VS Code to 1.70 the syntax highlighting of `=>` in `.vue` files changed. Also notice the `<` and `>` in tags.

Compare `.vue` with `.ts` file:

![2022-08-05_000235](https://user-images.githubusercontent.com/3753822/182952684-8e1b9385-50b7-4475-8e49-4eab90bb7931.png)

**Comment by James-Laidlaw** [comment]
this looks like the impact of issue #1566, although I believe the upgrade to VS Code 1.70  triggering it may be new information

**Comment by jb-qian** [comment]
open `/Users/${username}/.vscode/extensions/vue.volar-0.39.4-darwin-x64/syntaxes/vue.tmLanguage.json`

change
`
"begin": "([a-zA-Z0-9:-]+)\\b(?=[^>]*\\blang\\s*=\\s*(['\"]?)ts\\b\\2)",
`
to
`
"begin": "([a-zA-Z0-9:-]+)\\b(?=[^>]*\\blang\\s*=\\s*(['\"]?)\\ts\\b\\2)",
`
or
`
"begin":  #"([a-zA-Z0-9:-]+)\\b(?=[^>]*\\blang\\s*=\\s*(['\"]?)ts\\b)\\2",
`

reload vscode(v1.70.0)

it seems that it can be solved temporarily

**Comment by veritymedia** [comment]
Its freaking me out too. Thanks for the fix @jb-qian

**Comment by hackycy** [comment]
Its freaking me out too. 😩

**Comment by bcurtin144** [comment]
I think the problem is that the TextMate regular expression rules mark the `<script lang="ts">` tag _itself_ as TypeScript, at which point VS Code tries to apply bracket pair colorization and gets tripped up on the `>`, which continues on to other angle bracket symbols, like `=>`.

I'm definitely not an expert at TextMate, but it would seem that the solution would be to apply TypeScript rules only to what's _between_ the `<script lang="ts">...</script>` tags, and not the tags themselves.
