### ISSUE TITLE
Wrong import location with script setup

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/volar#178]
When I have two script tags and auto import something inside one, it imports it inside another tag.

```vue
<script lang="ts">
export default defineCom... <- auto import
</script>

<script setup lang="ts">
import { defineComponent } from 'vue' <- imports here

// I have some code here
</script>
```

**Comment by johnsoncodehk** [comment]
Hi @sheremet-va, TS auto import preferentially add import expression to the nearby exists import expression, In your case I think `<script setup>` has import expression but `<script>` have no.

This may be strange, but this is expected behavior.

**Comment by sheremet-va** [comment]
I had one import inside script tag and five imports inside setup.

Are you suggesting that one import was too far away?

**Comment by johnsoncodehk** [comment]
> I had one import inside script tag and five imports inside setup.
> 
> Are you suggesting that one import was too far away?

Not sure i understand your mean. 😅

Auto-import insertion priority order is:

- If already import module, insert to `{ ... }` from existing import expression.
- If `<script>` have import expression, insert to `<script>`.
- If `<script setup>` have import expression, insert to `<script setup>`.
- If no any import expression, insert to `<script>`.

You should decide whether the import expression is in `<script>` or `<script setup>` based on whether to expose import things to `<template>`.

**Comment by sheremet-va** [comment]
But it is not a TypeScript file per se. So I don't see the reason why it should import things outside of it's visible zone. eslint, for example, shows an error with `no-undef` rule. 

Also Volar doesn't automatically imports types as `import type` inside `script setup` which is frustrating since he starts to show me errors on the code that he automatically injected.

**Comment by johnsoncodehk** [comment]
`<script setup>` is syntactic sugar for `<script>` + `setup()`, `<script>` and `<script setup>` codes actually in the same TS file [by design](https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md).

E.g you can't import same properties from `<script>` and `<script setup>` twice and it will have runtime error. If Volar detect `<script>` and `<script setup>` as different TS file, we can't catch this error on IDE.

> Also Volar doesn't automatically imports types as import type inside script setup which is frustrating since he starts to show me errors on the code that he automatically injected.

This is another issue, you can open a new feature request issue. (But this function is very difficult to implement)
