### ISSUE TITLE
poor performance and takes up a lot of memory

### ISSUE THREAD

**Issue by C1oudust** [johnsoncodehk/volar#1794]
![image](https://user-images.githubusercontent.com/29059054/187572423-06d325d4-4a22-4541-af01-493e567cd5e5.png)

![image](https://user-images.githubusercontent.com/29059054/187572518-a257d478-f73a-479c-8837-7c4068bfc018.png)

**Comment by C1oudust** [comment]
The memory consumption of this plugin has even exceeded the Edge browser, and the following is the slow speed of auto-completion syntax prompts

**Comment by polk6** [comment]
same, I have uninstalled this plugin

**Comment by lwy1010** [comment]
是的，太占用内存了，智能代码提示也很慢，用的是插件的最新版本，本来以为是我装的其他插件的问题，后来把除了volar的插件全禁用了，问题依旧。刚看了其他类似的issue(#1529)，没想到已经有这么多人反馈占用内存和智能代码提示慢了...

**Comment by martijnenco** [comment]
Same, also disabling it..

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1615#issuecomment-1236852594.

**Comment by martijnenco** [comment]
@johnsoncodehk No, I'm not tracking bugs of every extension I have on vsCode.. Nor do I do workarounds unless I really have to.. ..It is disabled for now, if it's not fixt in some time I will uninstall it for good.

Dont have a workaround for something and call it 'fixed'. :)

**Comment by johnsoncodehk** [comment]
@martijnenco I can confidently say that I solved "all" overhead performance issues that I know. If you can provide a repro case or any useful information to help me find performance issues that I don't know, I'll see what can I do.

In fact most performance issues is from some big dependencies / poor project structure or TypeScript internal analysis, I have nothing can do if peoples just post screenshot or just say "I same".

I have no say "fixed" at all, the issue close because this is no help for confirm / find out problems from plugin.

> It is disabled for now, if it's not fixt in some time I will uninstall it for good.

If you don't consider the problem come from your project at all and also don't want to spend your time to help for find out problem, but just expect the plugin to magically solve it, sorry this plugin is not for your use case, please uninstall.
