### ISSUE TITLE
v-if type guard does not effect events

### ISSUE THREAD

**Issue by markbrockhoff** [johnsoncodehk/volar#1796]
Hi,

I noticed that the "type guard" functionality given by v-if effects props and the template but not events.

Example:
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/95471369/187711633-38ee1b98-45a2-4015-a68b-7552e58de390.png">

In this example I have a ref of an object called `selectedDepartment` the whole object can be undefined. To eliminate this case I use a v-if as a type guard to check that it is defined before using it inside the template.
This works like a normal if in typescript for the prop and template, but not the event.
I'd expect Volar to reduce the type of selectedDepartment to not be undefined like in the prop:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/95471369/187713282-2c7c553f-42fa-4da9-8cc8-923d45667bf3.png">

**Comment by xiaoxiangmoe** [comment]
This is because callback function may be called at any time.
For example:

```ts
setTimeout(()=>{
   emit('click')
  }, 100*1000);
```
This will emit click after 100s, but after component may be destroyed after 50s.
So the type narrow in callback function is unsafe.

---

But if you really want to use it. see https://github.com/johnsoncodehk/volar/issues/1750#issuecomment-1229232740

**Comment by markbrockhoff** [comment]
Ok, I see. Thanks for the quick answer.
