### ISSUE TITLE
Functional component args TS issues

### ISSUE THREAD

**Issue by theoephraim** [johnsoncodehk/volar#1943]
_UPDATE_

I think I may have just solved it by adding `const propsDefinition = {...} as const`, as you had mentioned in a previous comment somewhere.

But this stuff would be super helpful to add in the vue docs. Please if you can help clarify what the context arg should be, then I'll close this issue and open a PR to the info to the vue docs.

Thanks!

---

Hello again @johnsoncodehk!

It looks like something just changed and I am seeing issues again in VSCode around functional component props.
See https://github.com/johnsoncodehk/volar/issues/924 for previous discussion.

My functional component looks something like 
```typescript
const propsDefinition = {
  tagName: { type: String as PropType<"div" | "section">, default: "div" }
};

type FunctionalComponentPropsType<T> = InstanceType<DefineComponent<T>>["$props"];
type FunctionalComponentContextArg = any; // dont know what this should be...?

const MyFunctionalComponent = (
  props: FunctionalComponentPropsType<typeof propsDefinition>,
  context: FunctionalComponentContextArg,
): VNode => {
 //...

  return h(
    props.tagName || "div",
  );
}

MyFunctionalComponent.props = propsDefinition;
```

NOTE this problem only is appearing in vscode, not when I run vue-tsc, and it does not break anything.

If I remove the `MyFunctionalComponent.props = propsDefinition;` then Volar's typing seem to work, BUT setting the props like this affects the component behaviour, handling setting defaults, coercing booleans, etc - ie the normal behaviour you expect from non-functional components.

also sidenote - any idea what the context arg type should be?

Thank you so much!

**Comment by theoephraim** [comment]
Oh I think I may have just solved it by adding `const propsDefinition = {...} as const`, as you had mentioned in a previous comment.

This stuff would be super helpful to add in the vue docs. If you can help clarify what the context arg should be, I'll open a PR to add all this info to the vue docs.

Thanks!

**Comment by johnsoncodehk** [comment]
It seems that the problem is `MyFunctionalComponent.props = propsDefinition` narrowing `MyFunctionalComponent.props` type and make `MyFunctionalComponent` do not match `FunctionalComponent` interface anymore, you can try specify `MyFunctionalComponent` type to `FunctionalComponent` to fix.

```ts
const MyFunctionalComponent: FunctionalComponent<FunctionalComponentPropsType<typeof propsDefinition>, FunctionalComponentContextArg> = (
  props,
  context,
): VNode => {
 //...

  return h(
    props.tagName || "div",
  );
}
```

`context` arg type should be `{ attrs: XXX, slots: YYY, emit: ZZZ }`, you can see:
- https://github.com/vuejs/core/blob/9875ecd762155732008e397d450edb0f8c01b05c/packages/runtime-core/src/component.ts#L119
- https://github.com/vuejs/core/blob/9875ecd762155732008e397d450edb0f8c01b05c/packages/runtime-core/src/component.ts#L183-L188

But Volar only extract emit type from second type arg of `FunctionalComponent<Prop, Emit>` currently, and it can't resolve complex `context` arg type yet. (It could be a feature request)
