### ISSUE TITLE
The language of typeScript error prompt in *.vue file is confused

### ISSUE THREAD

**Issue by lucyanddarlin** [johnsoncodehk/volar#1959]
sometimes English, sometimes Chinese

<img width="722" alt="image" src="https://user-images.githubusercontent.com/78393023/194733205-9cf7f2b2-b561-4740-83e9-787bf181e502.png">
<img width="744" alt="image" src="https://user-images.githubusercontent.com/78393023/194733221-d3a818bc-a6be-4632-a926-10ad4388681f.png">

**Comment by lucyanddarlin** [comment]
the version of volar and vue-tsc is v1.0.1

**Comment by Cheng-DX** [comment]
Same

**Comment by Cheng-DX** [comment]
I got more version info:
- `vue-tsc v1.0.1` + `volar v0.40.13` works correctly
-  `vue-tsc v1.0.1` + `volar ^1.0.0` works wrong

**Comment by oliverzy** [comment]
I have the same issue with the latest version of Volar.

The display language in *.vue file should be English instead of Chinese.

**Comment by imyangyong** [comment]
same issue +1

**Comment by johnsoncodehk** [comment]
After checked the [source code](https://github.com/microsoft/vscode-languageserver-node/blob/2e2658c897fbd20e134076f685da005d173d5e92/client/src/node/main.ts#L558-L576) of vscode-languageserver-node, I think the problem is that it's using `process.env['VSCODE_NLS_CONFIG']` for language server language, but `process.env['VSCODE_NLS_CONFIG']` is system language instead of display language by default.

To fix this problem you can try change VSCode display language to any other language, and change back to `en`, it should force replace for `process.env['VSCODE_NLS_CONFIG']`.

**Comment by lucyanddarlin** [comment]
It seems to work!

**Comment by Cheng-DX** [comment]
Changing display language works to me

**Comment by johnsoncodehk** [comment]
I will make a pitch in vue language server in 1.0.5 to avoid this problem.

**Comment by lucyanddarlin** [comment]
thanks a lot!
