### ISSUE TITLE
Request completionItem/resolve failed.

### ISSUE THREAD

**Issue by 1059845833** [johnsoncodehk/volar#1983]
Today suddenly appeared, what is this

https://user-images.githubusercontent.com/59215561/195031446-bddf901a-7885-4f87-996b-81d80969f0fa.mp4

**Comment by 1059845833** [comment]
Message: Request completionItem/resolve failed unexpectedly without providing any details.

**Comment by 1059845833** [comment]
I tried but it didn't reproduce the problem.
This is what happens when I import "some" components (don't know what the difference)

This information comes from volar, maybe it's related to this? (did not exist before)
<img width="344" alt="image" src="https://user-images.githubusercontent.com/59215561/195317805-2ed256ba-6cd1-4ce3-886d-d857b32907b6.png">

**Comment by 1059845833** [comment]
> Could you try can this problem reproduce in https://github.com/johnsoncodehk/volar-starter?



> Could you try can this problem reproduce in https://github.com/johnsoncodehk/volar-starter?

I tried but it didn't reproduce the problem.
This is what happens when I import "some" components (don't know what the difference)

This information comes from volar, maybe it's related to this? (did not exist before)
<img width="260" alt="image" src="https://user-images.githubusercontent.com/59215561/195318313-b88d0b7d-1b77-4714-8018-a1c694e9c9c2.png">

**Comment by 1059845833** [comment]
> Could you try can this problem reproduce in https://github.com/johnsoncodehk/volar-starter?

I tried but it didn't reproduce the problem.
This is what happens when I import "some" components (don't know what the difference)

This information comes from volar, maybe it's related to this? (did not exist before)
<img width="326" alt="image" src="https://user-images.githubusercontent.com/59215561/195318466-1bbb7be0-91c3-4845-a686-be27d4d19df2.png">

**Comment by Mondotosz** [comment]
I'm having the same issue since a few days and the intellisense stopped working for imports.
I downgraded the `@types/node` package since that was on the known issues but it doesn't fix it.

Here I had suggestions for imports alongside their packages
![image](https://user-images.githubusercontent.com/55015209/195819075-27e0e6be-1760-44ff-bdff-f3f97a769f37.png)
Now I have to manually specify the source before I can get any suggestion which is pretty annoying
![image](https://user-images.githubusercontent.com/55015209/195819194-fc05b874-580f-47e5-823a-c6402040e8a7.png)

**Comment by vhud** [comment]
Same issue since the update on 10/14. The component gets imported properly but this error is annoying. Custom components color scheme changed as well, which I don't see mentioned anywhere on the changelog.
![vueFailed](https://user-images.githubusercontent.com/3059022/196036825-0f606828-eeee-44a8-b8d8-a78e8032d893.gif)

**Comment by johnsoncodehk** [comment]
@Mondotosz This is different problem, you can open a new issue for it.

@vhud, @1059845833 I can't reproduce this problem, could you provide repro case?

**Comment by 1059845833** [comment]
> @Mondotosz This is different problem, you can open a new issue for it.
> 
> @vhud, @1059845833 I can't reproduce this problem, could you provide repro case?
My latest project is in my repository (vue3-music), I have tested other projects (including vite and vue-cli) without reproducing the problem.
I re-clone this project and found no problem importing modules, the only difference with other projects is that the bottom tag will have a "1 known issue"(no response after clicking) message from volar , but my original project still have this problem.

**Comment by vhud** [comment]
@johnsoncodehk 
Have you tried creating a small vue cli project with the prior version of the plugin, then upgrading the plugin and attempting to create a new component? I'll try to nail down solid reproduction steps when I have more time, but this is something to try in the meantime.
