### ISSUE TITLE
Manually annotated prop should not be optional

### ISSUE THREAD

**Issue by rchl** [johnsoncodehk/volar#2032]
For this prop definition:

```js
  props: {
    items: {
      type: Array,
      default: () => [1, 2, 3]
    }
  },
```

Volar infers type of `items` as `unknown[]` in the template. Which is fine.

But when manually annotating type with JSDoc:

```js
  props: {
    /** @type {import('vue').PropOptions<number[]>} */
    items: {
      type: Array,
      default: () => [1, 2, 3]
    }
  },
```

The type is `number[] | undefined`. The problem being the `undefined` part. (This is regardless if `required: true` is specified or not but `true` is the default anyway).

This actually works correctly in `target: 2` mode with Vue 2.6 based project but not with Vue 2.7.

This code works as expected but I don't think it should be required:

```js
  props: {
    items: {
      /** @type {import('vue').PropType<number[]>} */
      type: Array,
      default: () => [1, 2, 3]
    }
  },
```

The definition of `PropOptions` is:

```ts
export interface PropOptions<T = any> {
  type?: PropType<T>
  required?: boolean
  default?: T | null | undefined | (() => T | null | undefined)
  validator?(value: unknown): boolean
}
```

so `type` is optional but that shouldn't influence the resolved prop value type IMO and it didn't in Vue 2.6.

**Comment by rchl** [comment]
Main branch on this repo reproduces this issue: https://github.com/rchl/volar-vue2-test

**Comment by johnsoncodehk** [comment]
You can try:

```
<template>
  <div>
    <div v-for="item in items">{{ item }} of {{ items.length }}</div>
  </div>
</template>

<script>
export default {
  name: 'Index',
  props: {
    items: {
      /** @type {import('vue').PropType<number[]>} */
      type: Array,
      default: () => [1, 2, 3]
    }
  },
}
</script>
```

**Comment by rchl** [comment]
I have written this example myself but as I wrote, I don't think that's the proper solution.

**Comment by johnsoncodehk** [comment]
This solution is no problem, when you write

```js
  props: {
    /** @type {import('vue').PropOptions<number[]>} */
    items: {
      type: Array,
      default: () => [1, 2, 3]
    }
  },
```

It was equivalence to 

```js
  props: {
    items: {
      type: Array as typeof import('vue').PropType<number[],
    }
  },
```

`default` option is remove because it's undefined by default in `PropOptions`, so `items` to be undefined able in template.

---

But with

```js
  props: {
    items: {
      /** @type {import('vue').PropType<number[]>} */
      type: Array,
      default: () => [1, 2, 3]
    }
  },
```

`default` option will not be remove.

Or you can also use this longer version.

```js
  props: {
    /** @type {{ type: import('vue').PropType<number[]>, default(): number[] }} */
    items: {
      type: Array,
      default: () => [1, 2, 3]
    }
  },
```

**Comment by rchl** [comment]
> `default` option is remove because it's undefined by default in `PropOptions`, so `items` to be undefined able in template.

Sorry but I'm still not convinced.

I guess you are explaining it from the point of typescript and its typing system and from that side it might make sense. But we are in Vue world and in Vue world a prop that has `default` value can't be undefined. So maybe Volar should account for that, if possible, and amend the types to match that?

Another simple example where the value should also never be undefined is:

```
    /** @type {import('vue').PropOptions<number[]>} */
    items: {
      type: Array,
      required: true,
    }
```

> Or you can also use this longer version.

That one only works in Vue 3 though.

**Comment by yoyo930021** [comment]
In vue 2.6 and lower, the vue type is not serious. It doesn't even deal with optional case. So no problem before.

When you try to use this code,
```
/** @type {import('vue').PropOptions<number[]>} */
items: {
  type: Array,
  required: true,
}
```
The type tool is only can get `PropOptions<number[]>` from `items`. it doesn't get `required` or `default` key.
In type information, we can't do anything in editor.

The volar is wrapper `defineComponent` from local vue package for type information.
If you think type definition is wrong, you can issue it in vue main project.

**Comment by rchl** [comment]
You are both smarter than me so I believe what you are saying. The reason that I'm still drilling it is because I don't fully understand it and I'm trying to understand where the problem is exactly.

What confuses me is that a code like this:

```ts
import { defineComponent } from 'vue';

const Component = defineComponent({
    name: 'Index',
    props: {
        items: {
            type: Array,
            required: true,
        }
    },
})

let cmp!: InstanceType<typeof Component>;

cmp.items
```

Shows that `cmp.items` is non-optional array but if I remove `required: true` then it correctly shows that it's optional.

![Screenshot 2022-10-25 at 08 52 17](https://user-images.githubusercontent.com/153197/197702817-fc11eb3f-5476-40f4-bf79-65aeeccbabc9.png)

So the issue is related to JSDoc annotations and I don't understand why it behaves differently when using JSDoc.
I'm guess that maybe it's a limitation of JSDoc support in Typescript?

Note that I'm not able to get JSDoc working in that example above. I'm not sure what Volar/Vetur does differently to get this to work in a real Vue component.

---

BTW. Semi related question. Is `__VLS_Ctx` type (with upper-case `C`) in https://github.com/johnsoncodehk/volar/blob/912bb52fc79319cd04c6a178ca43b93cfb005378/vue-language-tools/vue-language-core/src/generators/script.ts#L605-L605 defined anywhere? I've been looking for a while but couldn't find it anywhere.

**Comment by yoyo930021** [comment]
First, your problem is from vue type definition, not vetur or volar.
It was a misunderstanding about vetur and volar.

Vetur doesn't support vue 2.7 now, so it will wrapper `Vue.extend` in this project. This is a mistake.
So it's actually using the vue 2.6 type definition.
In vue 2.6 and lower, the vue type is not serious. It doesn't even deal with optional case. So no problem before.
If you try to wrapper `defineComponent` in your code, vetur will get same type with volar.
![截圖 2022-10-26 上午11 24 23](https://user-images.githubusercontent.com/9126398/197927262-7e0fc410-d791-473f-a9d0-c1128b91420e.png)

Volar will wrapper `defineComponent` when `target: 3` or default.
It's a new type definition in vue 2.7 and 3.

So your problem is essentially the difference between `Vue.extend` and `defineComponent` type definition.

Volar and volar use same method for getting vue component props/data/computed type. They are based on `InstanceType`.
The vue component type information is from vue package type definition in your project. Like `Vue.extend` and `defineComponent`.

Let me analyze the difference:
#### `Vue.extend`
The `Vue.extend` will only try to get `T` type, not deal with optional and undefined.

code:
- https://github.com/vuejs/vue/blob/main/types/vue.d.ts#L282
- https://github.com/vuejs/vue/blob/main/types/options.d.ts#L144
- https://github.com/vuejs/vue/blob/main/types/options.d.ts#L293

#### `defineComponent`
The `defineComponent` will try to deal with optional and undefined.

code:
- https://github.com/vuejs/vue/blob/main/types/v3-define-component.d.ts#L73
- https://github.com/vuejs/vue/blob/main/types/v3-define-component.d.ts#L33
- https://github.com/vuejs/vue/blob/main/types/v3-component-props.d.ts#L71

Let me see your code:
The `PropOptions` is define `default` key optional. https://github.com/vuejs/vue/blob/main/types/v3-component-props.d.ts#L15
When you set `/** @type {import('vue').PropOptions<number[]>} */`, the default key is optional.
If you want to maintain the same behavior as before, we need to defind `default` key not optional or `required` key not optional in `PropOptions`  type definition. So you should go to the main vue project and send an issue to discuss with them how to make the change.
