### ISSUE TITLE
No new line for html element in template

### ISSUE THREAD

**Issue by henrychea** [johnsoncodehk/volar#2246]
When formatting with Volar, the html element is not put on a new line. However, you can see that indentation works correctly. I think maybe my settings are wrong or Volar is not making new lines correctly. 

Btw this is my VS Code format setting:
```
"[vue]": {
  "editor.defaultFormatter": "Vue.volar"
}
```

https://user-images.githubusercontent.com/40254517/209094856-576749f2-bd7a-4b54-84ba-dd3df0d77748.mov

**Comment by johnsoncodehk** [comment]
This is expected behavior of [vscode-html-languageservice](https://github.com/microsoft/vscode-html-languageservice), to change it you can use https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettier or https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/prettyhtml instead of.
