### ISSUE TITLE
[FEEDBACK] Is Takeover Mode the only solution!?

### ISSUE THREAD

**Issue by angelhdzmultimedia** [johnsoncodehk/volar#2292]
**I used to be excited about Vue.**

Not anymore with Volar's _Takeover Mode_.

It's a pain creating a project and remembering half through it "Oh right, I have to disable built-in TypeScript extension for this workspace" and then reloading the workspace.

Then you open a new project in the same workspace, but somehow it becomes a new workspace and you have to do the steps again.

Really this is the only way to solve these TypeScript/Vue issues!?
No other people working in other solutions!?

This is the only language I have to do all these gymnastics.
Not in Python, not in Dart and Flutter. Not in C#. And not in React or Svelte.

So much wasted time configuring the editor and configuration files instead of creating and being productive.

 I know I can do it the old way, letting Volar and TypeScript Vue Plugin (Volar) extensions have 2 TS language servers, but as per the docs, it's slow and not encouraged, but I'm being tempted to go back to this approach.
 
Note:  I greatly appreciate the work and effort of the Volar team,  I don't intend to cause any inconvenience, I'm just expressing my frustration and reaching out for a practical solution.

**Comment by johnsoncodehk** [comment]
> It's a pain creating a project and remembering half through it "Oh right, I have to disable built-in TypeScript extension for this workspace" and then reloading the workspace

When your project is using takeover mode and opened a .ts file, the VSCode status bar will append `(vue)` to the TS version, and you should judge if takeover mode is enabled based on it but not remembering it.

<img width="68" alt="螢幕截圖 2023-01-08 09 50 10" src="https://user-images.githubusercontent.com/16279759/211177556-f815a3cd-08d7-49a9-b9b0-a1a8edf9d965.png">

> Then you open a new project in the same workspace, but somehow it becomes a new workspace and you have to do the steps again.

This is beyond Volar's control, but for your need, you can track https://github.com/microsoft/vscode/issues/40239.

> Really this is the only way to solve these TypeScript/Vue issues!?

You answered the question yourself, you can also use the TS plugin, TS plugin is always available and actively maintained.

> No other people working in other solutions!?

I can't speak for other frameworks, only for Vue, we have at least explored solutions on top of Vetur, VueDX, Volar by different team members, I want to emphasize this point because your statement gives the impression that we just give solutions arbitrarily, which seems to be negating the efforts of all the people involved in these efforts.

---

This is not a problem from TypeScript/Vue. Other frameworks (Angular, Svelte, Astro...) solutions are almost all based on TS plugin. The difference with Vue is just that we not only implemented TS plugin, but also pointed out its shortcomings (these shortcomings also exist in other frameworks) and "additionally" provides takeover mode as an alternative, but takeover mode is always optional. So it's unfair if you think this is a disadvantage compared to other frameworks.

**Comment by angelhdzmultimedia** [comment]
> "So it's unfair if you think this is a disadvantage compared to other frameworks."

See? I didn't want to engage in a debate, but you already played the victim and I was afraid that's what would happen, instead of taking constructive criticism. That's what nowadays happens, people are hyper-sensitive and feel special and can't take anything. But I took a leap of faith and told to myself "everything is gonna be alright, they are gonna reply you kindly and nothing is going to get personal, don't overthinking, go ahead, post it".

I was expressing my frustration, not fair being in defensive mode and attacking me implying I'm attacking this technology and promoting others or not appreciating the effort of the team because that's evidently false. I was promoting this extension along with Vue, Nuxt, Quasar and was very happy and hyped, and I've helped a lot of people around the world for free.

Your arrogant comment came out as "we are a team of infalible, genius people, and we know our decision is right, and if you think otherwise, you are wrong". Having to uninstall an extension to get something working it's clearly a hack, even if thousand people decided on it. Millions of people vote for the wrong politicians all the time, that doesn't make them right or smart.

> "and "additionally" provides takeover mode as an alternative"

You putting "additionally" between quotes is false, and **this is exactly why I made this issue in the first place**, because Takeover Mode is being **recommended** with a warning icon, instead of being provided as an alternative. That's why I used Take Over mode since I got some error previously using only the Volar extension and was recommended in this repository to use Take Over mode. But now that I found out it isn't actually mandatory, and that I can install TypeScript (Volar) extension, even if it's slower, I don't have to disable built-in TypeScript extension for every workspace. 


![image](https://user-images.githubusercontent.com/10191085/211178465-1f0676ef-6eb9-4018-8a44-cb0bc4ef8297.png)

I know you aren't going to accept that your reply was in defensive mode (I have been replied by other maintainers and I can tell when someone really is kind and wants to help and have people skills, or when someone just want to feel superior and goes all righteous). And because I didn't feel welcome here, I will stop creating issues, and will be looking in the Vue official platforms for any issue/solution with this extension for VSCode.

And it's funny and ironic how many people promoting their products go all "Have any feedback? Feel free to let us know!" when they want to get their products promoted, but when people actually have feedback, **THIS HAPPENS**...

However, I'm still gonna wish you success and health, and thank you for the effort put on this extension, that have allowed me have my mind focused creating stuff with Vue, instead of overthinking, due to my Generalized Anxiety and Depression, 
and which I recommended many people to switch from Vetur to Volar.

**Comment by johnsoncodehk** [comment]
First of all, thank you for your help with the community.

You may not have seen some of the offense in your comments and you seem to have assumed the community was malicious before you commented. You need to know that I would be equally frustrated to see your frustrating comments. If your goal is to improve our UX/DX through discussion, I'm sure you can do a better job.

> we are a team of infalible, genius people, and we know our decision is right, and if you think otherwise, you are wrong

I don't know how you came to your opinion. I'm just average and often wrong (really), and all I'm arguing against is your emotionally thank that we're not doing too much for it. And comparing to frameworks with an incorrect opinion.

> Having to uninstall an extension to get something working it's clearly a hack, even if thousand people decided on it.

I don't think so. (But that's not the point, so it's not discussed here to avoid threads getting confused)

> You putting "additionally" between quotes is false, and this is exactly why I made this issue in the first place, because Takeover Mode is being recommended with a warning icon, instead of being provided as an alternative.

The warning icon is just there to make sure the user notices it. And it does say "recommended" rather than mandatory. If you think it is misleading, it would be good to open a PR to improve it.

---

If you want a more friendly reply please avoid unnecessary anger first (bold and exclamation marks are not necessary). I see you have another old issue, which is good.

Obviously you're mapping your feelings from elsewhere to here, and I'm sure you're not the only one getting negative feedback from the community, so if you can't adjust your mindset I suggest you stay away from it for a while rather than allowing yourself to be who you say you are.

**Comment by johnsoncodehk** [comment]
> I know you aren't going to accept that your reply was in defensive mode (I have been replied by other maintainers and I can tell when someone really is kind and wants to help and have people skills, or when someone just want to feel superior and goes all righteous). And because I didn't feel welcome here, I will stop creating issues, and will be looking in the Vue official platforms for any issue/solution with this extension for VSCode.
> 
> And it's funny and ironic how many people promoting their products go all "Have any feedback? Feel free to let us know!" when they want to get their products promoted, but when people actually have feedback, **THIS HAPPENS**...
> 
> However, I'm still gonna wish you success and health, and thank you for the effort put on this extension, that have allowed me have my mind focused creating stuff with Vue, instead of overthinking, due to my Generalized Anxiety and Depression, and which I recommended many people to switch from Vetur to Volar.

I didn't see a paragraph in my reply (it was blocked by a large picture), but in fact it made me feel much friendlier and I hope you are actively improving your condition and your mental and physical health.

**Comment by Cyclodex** [comment]
Coming from the https://github.com/microsoft/vscode/issues/40239 case, and searching for the "right" setup to have a good Developer Experience with Vue tooling... And just as a said note, everything is meant in a positive way, and I would like to understand and help the community or devs to clarify the situation a bit.

(Little off topic, but) I also feel it's not so easy to get the right setup with the right tools working, just because there are multiple ways of how we can solve it. Sure the community is big and has different approaches, but with vue 2 it was already a pain, which tools to use and how to configure them (Vetur, DX, now volar as well, etc.)

I hoped this will be better with Vue 3, and thought/hoped Volar is the "only" right/supported solution and struggled with the 2 shown extensions in vscode for Volar. The warning sign also made me feel "warned - like a deprecation message".

Question is, what's the best approach to have Vue 2 & Vue 3 projects working nicely together right now ? As lots of developers will probably still work with both Frameworks until every old one is shutdown or migrated.

I was wondering if it would be worth creating an extension which could check, which extensions are enabled and then suggest to the user to disable or enable the specific modules for best support until VSCode can handle it automatically or better, with profiles or whatever. What do you think?

Would the simpler solution be, to use Volar for both Vue2 and Vue3, or should we use Vetur + Volar + plugin?
Or stick to Vetur? Thanks for any help or clarification about the difference here. Maybe you also have a link to a page where everything is described better?

**Comment by Cyclodex** [comment]
I have now created a VSCode extension, which will check "unwanted recommendations" and warn the user if they are still enabled. (VSCode can not do it automatically yet)

This can greatly help to keep the project working across bigger teams.
Feel free to check it out here: https://marketplace.visualstudio.com/items?itemName=GARAIOAG.garaio-vscode-unwanted-recommendations

**Comment by johnsoncodehk** [comment]
@Cyclodex It's a smart idea. 👍

**Comment by angelhdzmultimedia** [comment]
@johnsoncodehk I want to apologize for the way I replied.

As you noticed, it was having a very hard time with many things that paid a toll on my health and I exploded finding a solution because I felt lost about what to do and what approach to follow.

And because my generalized anxiety and depression, I overthink things, in a huge way.

I use to be very kind when I reply, and even when I help people, because I'm using all these technologies to make tutorials for free to help people start working with them, and because I don't want and I can not have arguments with people.

I'm not perfect, and no one else is. And it's a very important thing as an human being to apologize when you do things wrong.

I know I could have handled this a better way. 

I also have to deal with consumers of my tutorials, who on top that I'm making them for free, they have high expectations and demands, like for example they want me to speak with a microphone, otherwise my videos are of "poor quality". They can't even understand the panic attacks I suffer, and the anxiety. It's a miracle I'm even making these tutorials in the first place.

Thanks for being patient and kind, and still trying to help me solve this problem after my explosion.

And as I mentioned, my intention was to find a definitive route to follow, not to bash this extension or anything.

I still promote it, and Vue, and Nuxt, and Quasar and I'm having fun with it, and I can't stand when people talk bad about Vue and about its creator. I have even been tempted to comment and defend them 😂, but nah, I can't for my health.

But yeah I've noticed a pattern where other frameworks are more supported and promoted than Vue and I can't understand why, because Vue (and with script setup) has a looot of benefits. And with Nuxt 3? Perfect combo! 🔥

I still haven't had the opportunity to start contributing in these open source projects in the source code, but I hope doing it soon.

**If you think this issue should be deleted (and I think it should), please do it.**

With all my heart ❤ I want to apologize for any inconvenience my issue caused, and let you know that from the day I opened this issue, to this day, I've made changes in myself as an human, I started to minimize the need to argue or be in defensive mode (there are a lot of maintainers that are rude and that have made me paranoid). 

And congratulate you for all the hard work you have been doing. 🔥🎉🤝

Wishing the Volar team health, peace, and success.

**Comment by johnsoncodehk** [comment]
@angelhdzmultimedia Sorry for the delayed response (I received too many emails), and thank you for taking the time to reply. I'm glad to hear that you're going better, and I hope you can maintain good progress with a relaxed mindset. If you like anime, I recommend "Kenichi: The Mightiest Disciple". It miraculously improved my mindset before when I couldn't digest the malice of the open source community, it may also be suitable for you.

Afterwards, we changed the display from "(vue)" back to "(takeover)", which should solve the problem.

Keeping the issue is fine. We've rarely deleted issues, even if they were very much crude. But if you want me to delete it, please let me know, and I will respect your wishes.
