### ISSUE TITLE
Issues when used in conjunction with remote ssh

### ISSUE THREAD

**Issue by robokozo** [johnsoncodehk/volar#239]
I think there might be some compatibility issues with Volar and VS Code Remote Explorer feature/extension.

https://code.visualstudio.com/docs/remote/ssh

![image](https://user-images.githubusercontent.com/1719221/120365694-a0f8c000-c2c3-11eb-8a6d-f6feea6553d5.png)

As you can see in the image, I've opened the same file twice but only my local instance of the project gets the toggles for ref sugar / pug templates and also the ability to suggest imports.

I've started to primarily work out of remote ssh these days so I would love to have the full power of Volar available to me there too.

EDIT: And yes, I have installed Volar on the SSH Host

**Comment by johnsoncodehk** [comment]
Sorry for the delay in dealing with this problem because I don't have a ready-made ssh server. Recently I checked on WSL and all language features (including codeLens) seem working good.

The version difference is too big for me to track down the cause. The problem may come from volar/vscode/LSP/settings(`"editor.codeLens": false`). If you still have this problem in the latest version of vscode and volar, please try to provide reproduce and more system info(Run `Help: About` command in vscode).

**Comment by robokozo** [comment]
While the above reported issue hasn't "bothered me" as much, one thing that I've been struggling with a lot lately is the intellisense when using the typescript alias on a remote environment. See below:

Remote Absolute:

![image](https://user-images.githubusercontent.com/1719221/147955566-37c2191a-ea39-484d-b417-1ee31aefec0a.png)

Local Absolute: 

![image](https://user-images.githubusercontent.com/1719221/147955587-4457411c-ab9a-4648-90d0-02c6a3931fc0.png)

Remote Relative:

![image](https://user-images.githubusercontent.com/1719221/147955655-88f5c4fe-333b-43b7-9119-123798e2863d.png)

Any ideas?

Thank you <3
