### ISSUE TITLE
script-setup: A module cannot have multiple default exports

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#383]
To declare properties that script-setup doesn't support, one should create a regular script tag with a default export, which will be merged with script-setup by SFC compiler.

It seems Volar doesn't support that properly, as I get an error: _A module cannot have multiple default exports_.

![image](https://user-images.githubusercontent.com/3832820/129892237-d3240d5c-193e-4b47-b0bc-14b6ad1f9214.png)

**Comment by johnsoncodehk** [comment]
Please replace `export default ({ ... })` to `export default { ... }` or `export default defineComponent({ ... })`, otherwise volar don't know it.

**Comment by jods4** [comment]
The first two should be the same, shouldn't they?
Notice that without brackets, strangeness ensues:
![image](https://user-images.githubusercontent.com/3832820/129893131-ba06cb4c-856d-4c59-a2cc-84e114e2e80d.png)

**Comment by jods4** [comment]
Interestingly, it's fixed when I remove the comma.
I wonder what syntax ambiguities are at play here... 
We use prettier and it adds the comma automatically 🤔

`defineComponent` seems to be the only option that works without error in this case.

Not specific to Volar: it's a bit strange and confusing that imports from one script block are in effect in _another_ script block.

**Comment by johnsoncodehk** [comment]
> The first two should be the same, shouldn't they?

The ast generated by this two cases is not same. Unless there is a practical need, I will avoid writing a complicated parser to handle all edge cases and avoid becoming a legacy technical debt.

> Notice that without brackets, strangeness ensues:
> ![image](https://user-images.githubusercontent.com/3832820/129893131-ba06cb4c-856d-4c59-a2cc-84e114e2e80d.png)

Because `export default` has been remove in virtual file, so the statement syntax is broken, will fix it.

<img width="168" alt="螢幕截圖 2021-08-18 下午8 01 57" src="https://user-images.githubusercontent.com/16279759/129894927-c5ff7775-5cd7-487d-8f73-ab707d5cd319.png">

**Comment by jods4** [comment]
I'm reopening to track the `export default` removal bug, then.
