### ISSUE TITLE
Incorrect Problem Reported with VeeValidate

### ISSUE THREAD

**Issue by JohnCampionJr** [johnsoncodehk/volar#41]
Hi, made a test repo, thinking this was an issue with VeeValidate.   But the error only appears in VS Code with Volar.  Vetur does not indicate this problem, which leads me to think its a Volar issue.

https://github.com/JohnCampionJr/vee-validate-vue3-ts

Volar throws an error in the validation page, with the VeeValidate Form submit handler having more than one property.

**Comment by johnsoncodehk** [comment]
Hi @JohnCampionJr, the `onSubmit` function is not matching for `@submit` emit type,  Vetur no errors because it do not support events type checking.

The original `@submit` type of `(payload: Event) => void` is come from [vue library](https://github.com/vuejs/vue-next/blob/master/packages/runtime-dom/types/jsx.d.ts#L1224), if `@submit` of `vee-validate` From should be other type, `vee-validate` should define they own `onSubmit` prop to override the original type. You should open a issue to `vee-validate` for that.

**Comment by JohnCampionJr** [comment]
OK, I've contacted them, thanks.

**Comment by logaretm** [comment]
Hello @johnsoncodehk, vee-validate author here. great work with volar.

I tried adding a `onSubmit` prop like you suggested on the `Form` component and it didn't work, it tries to match it to both `(payload: Event) => void` and the custom vee-validate type.

```
Type '(values: Record<string, any>, actions: any) => void' is not assignable to type 'SubmissionHandler<Record<string, any>> & ((payload: Event) => void)'.ts(2322)
```

Any pointers?

**Comment by johnsoncodehk** [comment]
Hi @logaretm, sorry I just found this is a types bug from Volar when props duplicate name with `HTMLAttributes`. I will publish a new version to fix now.

**Comment by JohnCampionJr** [comment]
You are both amazing coders - thanks for fixing this!

**Comment by johnsoncodehk** [comment]
please try 0.19.6.

and I found a other problem you may need to note. your component name `Form` is duplicate name with native elements, so props autocomplete is broke, if you need autocomplete, you need to rename `Form` for now, I will fix it.

<img width="786" alt="螢幕截圖 2021-01-11 上午8 01 56" src="https://user-images.githubusercontent.com/16279759/104139192-9dcc6880-53e4-11eb-8f0f-b2286b6f6b7c.png">
