### ISSUE TITLE
how to disabled volar template format

### ISSUE THREAD

**Issue by hcwhan** [johnsoncodehk/volar#425]
now, I use eslint-plugin-vue and rule `vue/max-attributes-per-line`  `vue/singleline-html-element-content-newline`
when use format, I can see eslint-plugin-vue change code For a moment volar change again , As shown
![GIF 2021-8-27 9-25-39](https://user-images.githubusercontent.com/7278897/131056987-2cb18feb-e5a3-4d14-b50a-2294c1a107d3.gif)
So, how to disabled volar template format? only use eslint fix format. 
tks

**Comment by 2malh** [comment]
Hey there,
as mentioned on the Vue Discord server I'm having the exact propblem but I can't figure out how to disable the formatting by ESlint and/or Volar. Now I've copy & pasted your settings into my user, workspace and folder settings but it still doesn't work. 

Here are some of the settings I've played around with. Any idea how to get Prettier running?

```json
{
  "volar.tsPlugin": true,
  "volar.icon.preview": true,
  "volar.icon.finder": true,
  "eslint.format.enable": false,
  "editor.formatOnSave": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[vue]": {
    "editor.formatOnType": false,
    "editor.formatOnSave": false
  },
  "editor.codeActionsOnSave": {
    "source.fixAll": false,
    "source.fixAll.eslint": false
  },
  "eslint.workingDirectories": ["./frontend"],
  "prettier.enableDebugLogs": true,
  "prettier.useEditorConfig": false,
  "prettier.enable": true
  "eslint.format.enable": false,
  "prettier.enable": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
}```

I have also installed the Pretier-ESlint extension hopeing that I can somehow override everything else but it's just now working -.- Prettier is working as expected if I manually format via `CMD + Shift + P` -> `Format Document with...` but get's reset everytime I save the file afterwards.

Help highly appreciated :)

**Comment by johnsoncodehk** [comment]
@2malh have you try `Format Document with..` -> `Configure Default Formatter...` -> `Prettier`?

**Comment by 2malh** [comment]
> @2malh have you try `Format Document with..` -> `Configure Default Formatter...` -> `Prettier`?

Yes, absolutely. As you can see above I have `"editor.defaultFormatter": "esbenp.prettier-vscode"` set globally, for [javascript] and I've tryed it for [vue] as well.
Problem is that if I `disable editor.formatOnSave` I don't think that Prettier is ever going to be called.

**Comment by johnsoncodehk** [comment]
@2malh not sure I understand your needs, do you want to use Prettier automatic formatting when saving vue documents? If yes you just need to set this:
```json
{
	"[vue]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode",
		"editor.formatOnSave": true
	}
}
```

**Comment by 2malh** [comment]
I'd love it to be that easy. Activating the formatting like this unfortunately reintroduces the same glitch as you can see in the gif from OP :( So there must be somethting else (ESlint? Volar?) doing it's formatting job too. I'm pretty sure the problem is on my side having something set wrong but so far I haven't found what it is.

**Comment by johnsoncodehk** [comment]
@2malh the gif problem is ESLint format and VSCode format working at the same time, I don't use ESLint so I can't help, please google "How to disable eslint formatting".

**Comment by 2malh** [comment]
Well, I've given this a couple more tries without having a clear conclusion but ESlint and Prettier are on the same page when it comes to formatting. Given this line:

![grafik](https://user-images.githubusercontent.com/42282368/131667658-f21afda0-259d-477a-b557-dbb9ca7b63da.png)

If I go `Format Document with...`-> `ESLint` or `Prettier`both format this line to this:

![grafik](https://user-images.githubusercontent.com/42282368/131667806-0d5113b7-f9ff-4313-96ac-b8270fad442a.png)
Same thing happens if I run `npx eslint --fix thatfile.vue` or `npx prettier --write thatfile.vue`

But if I now hit save it goes back to the previous single-line formatting which is marked as error.
ESLint is following Prettier rules as can be seen here

![grafik](https://user-images.githubusercontent.com/42282368/131668020-cfd5cf7b-c8a9-4750-8ec5-6b41fb54bc21.png)

So ESLint and Prettier both would love to split this line but it's not happening because of something else.
Is there even the slightest possibility that Volar is doing some kind of formatting?

**Comment by johnsoncodehk** [comment]
It sounds like the problem is that you did not succeed in setting ESLint or Prettier as the default formatter. I can try to check your setting, please @ me in Discord.

**Comment by 2malh** [comment]
Just in case someone else might have this problem in the future: It was the Headwinds extension that collisions with Prettier ^2.3.0 

Relevant issues:
https://github.com/prettier/prettier/issues/10918
https://github.com/heybourn/headwind/issues/127

Prettier/eslint worked fine but headwinds reformattet everything into a single line.
Now I'm locked on Prettier 2.2.1 and it works

**Comment by nolimitdev** [comment]
By disable VSCode built-in formatter `"javascript.format.enable": false` Vue.volar does not format script tag any more. Undocumented feature :)

**Comment by johnsoncodehk** [comment]
> `"html.format.enable": false` does not disable it.

It should do(implement at https://github.com/volarjs/plugins/blob/a734f87f0ae8903c00e3ff2c4db3350cc2ca1e75/packages/html/src/index.ts#L128-L130), please open a bug report if not works.

**Comment by bjwktcsnzh** [comment]
Write these to `./.vscode/settings.json` . It work for me .

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
  },
  "vue.codeActions.enabled": false,
  "vue.codeLens.enabled": false,
  "vue.autoInsert.dotValue": true,
  "vue.inlayHints.missingProps": false,
  "vue.inlayHints.optionsWrapper": false,
  "vue.splitEditors.icon": false,
  "vue.server.reverseConfigFilePriority": false,
  "vue.server.petiteVue.supportHtmlFile": false,
  "vue.updateImportsOnFileMove.enabled": false,
}
```

I use these extensions ( in `./.vscode/extensions.json` ): 

```json
{
  "recommendations": [
    "gruntfuggly.todo-tree",
    "editorconfig.editorconfig",
    "dbaeumer.vscode-eslint",
    "ecmel.vscode-html-css",
    "vue.vscode-typescript-vue-plugin",
    "vue.volar"
  ]
}
```
