### ISSUE TITLE
vue-tsc check error

### ISSUE THREAD

**Issue by liuzw2579** [johnsoncodehk/volar#467]
my project open with volar will get this:
![image](https://user-images.githubusercontent.com/30503937/132437044-a2a1689b-a2a0-4749-b30c-67d41afd7700.png)
but my devDeps is this:
![image](https://user-images.githubusercontent.com/30503937/132437115-3aa2c3a5-8eb2-4a86-9f5e-64a73efddff9.png)

**Comment by johnsoncodehk** [comment]
0.27.11 is vue-tsc's dependency vscode-vue-languageservice version, please check node_modules/vscode-vue-languageservice/package.json.

**Comment by colinbes** [comment]
So what's best way to figure out compatibility between Volar and vue-tsc? Maybe I am missing some salient point.

**Comment by johnsoncodehk** [comment]
@colinbes vue-tsc is just a cli interface for volar, should not have compatibility problem.

Usually you just need to keep the node_modules/vscode-vue-languageservice version consistent with the VSCode volar version.

**Comment by colinbes** [comment]
Am I correct that install vue-tsc installs vscode-vue-languageservice as well? Appear this way to me. 

I honestly don’t understand why I see this error pop up now and again as my versioning doesn’t change very often and vue-tsc has not seen many changes lately since 0.3.0.

My latest message that popped up said vue-tsc’s dependency version (0.27.23) is different from extension version (0.27.26)….

If I look at package.json under node_modules/vscode-vue-languageservice I see:

  "name": "vscode-vue-languageservice",
  "version": "0.27.26",

And looking at node_modules/vue-tsc I see:

  "dependencies": {
    "vscode-vue-languageservice": "^0.27.0"

I can’t find any dependencies anywhere show 0.27.3 (used search in files)

So guess all boils down to what installs node_modules/vscode-vue-languageservice

Thanks for your response.

~Colin

Internet Disclaimer
_________________

This message (including any attachments) contains confidential information intended for a specific individual and purpose, and may be protected by law. 
If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.
_________________

**Comment by johnsoncodehk** [comment]
<img width="424" alt="螢幕截圖 2021-10-02 上午1 16 26" src="https://user-images.githubusercontent.com/16279759/135697984-6c7607e4-c119-487f-97c2-5e272990115c.png">

Please check which file you were navigated to when you click "Open package.json"?

**Comment by colinbes** [comment]
Will do if it comes up again.

**Comment by colinbes** [comment]
It just happed again, this time stating that 0.27.26 is different to extension version 0.27.28

Clicking on open package.json took me to vscode-vue-languageservice’s package.json with cursor on line stating repository:
{
  "name": "vscode-vue-languageservice",
  "version": "0.27.26",
  "main": "out/index.js",
  "license": "MIT",
  "files": [
    "out/**/*.js",
    "out/**/*.d.ts"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/johnsoncodehk/volar.git",
    "directory": "packages/vscode-vue-languageservice"
  },

Running npm uninstall vue-tsc, npm clear cache –force, npm install -D ***@***.*** updated vscode-vue-languageservice’s package.json version to 0.27.28

~C
