### ISSUE TITLE
[FR] Highlighting components within templates

### ISSUE THREAD

**Issue by akaufmann** [johnsoncodehk/volar#522]
Would it be possible to highlight components in templates like in Svelte/React?

Vue (Volar)
![Bildschirmfoto 2021-09-23 um 16 57 06](https://user-images.githubusercontent.com/288499/134531856-098ebdf9-960b-4de1-810e-a7a0a93a26d7.png)

Svelte
![Bildschirmfoto 2021-09-23 um 17 01 35](https://user-images.githubusercontent.com/288499/134532322-46355600-973f-45fe-ad60-990e4ac7345c.png)

**Comment by johnsoncodehk** [comment]
VSCode has default config `"editor.semanticHighlighting.enabled": "configuredByTheme"` so it may disable by some theme extensions, you can config `"editor.semanticHighlighting.enabled": true` to force enable it.

**Comment by RennCheung** [comment]
Sorry, I didn't find the right Issuse, I used the unplugin-vue-components in the project he can automatically introduced, but this will cause the component color to be red, it seems that volar does not resolve his introduction.

![image](https://user-images.githubusercontent.com/50518861/135194063-cd938397-bd05-4c01-a042-35314daf50c1.png)

I have to introduce components through import, and he will display the correct color.
![image](https://user-images.githubusercontent.com/50518861/135194116-c1383822-3153-474b-8884-f1c9dd12ed22.png)
![image](https://user-images.githubusercontent.com/50518861/135194135-37e60093-bed8-4a9e-ae30-bedcc6104846.png)

**Comment by johnsoncodehk** [comment]
@RennCheung make sure you config correctly, see https://github.com/antfu/unplugin-vue-components#typescript

**Comment by RennCheung** [comment]
Sorry, it was my negligence.👍

**Comment by AradAral** [comment]
@johnsoncodehk Setting `editor.semanticHighlighting.enabled` to `true` fixed this, but I'm curious why is it that the Svelte extension, for instance, shows the right color (green) on components even when `editor.semanticHighlighting.enabled` is `false` or `"configuredByTheme"`?!
Whatever they're doing, can't Volar adopt the same technique to avoid confusion?

**Comment by johnsoncodehk** [comment]
> but I'm curious why is it that the Svelte extension, for instance, shows the right color (green) on components even when `editor.semanticHighlighting.enabled` is `false` or `"configuredByTheme"`?!

I don't think you can say svelte show correct green color, it just always show green color, but append an error.

<img width="1232" alt="螢幕截圖 2021-12-04 上午12 58 51" src="https://user-images.githubusercontent.com/16279759/144642765-474b3ec5-f031-4b60-86a0-f48a387c7b9f.png">

On the contrary, I think at least for now, show an error is too radical for vue users, so it just shows a different color but no error.

`editor.semanticHighlighting.enabled` behavior is designed by vscode, so you can consider blaming vscode instead of volar.

**Comment by AradAral** [comment]
@johnsoncodehk But the point here is that sometimes in Volar the component is properly imported, but it's still red, like:
This is solved by setting `editor.semanticHighlighting.enabled` to `true`, but Svelte extension doesn't have this problem even when `editor.semanticHighlighting.enabled` is `false`:

![image](https://user-images.githubusercontent.com/26527405/144650278-3636069a-0f05-4394-97a0-a22eaaeb03b7.png)

**Comment by johnsoncodehk** [comment]
@AradAral I did not misunderstand what you mean.
What I mean is that vscode defaults `editor.semanticHighlighting.enabled` to `configuredByTheme ` to cause this problem, which is not controlled by Volar.
There is no problem with svelte, just because svelte does not support displaying different colors, not because svelte solves this problem.

**Comment by AradAral** [comment]
> What I mean is that vscode defaults editor.semanticHighlighting.enabled to configuredByTheme to cause this problem, which is not controlled by Volar.

Sure :) I'm asking why doesn't Volar color highlighting work as expected regardless of the value of `editor.semanticHighlighting.enabled`? Like Svelte does?

**Comment by johnsoncodehk** [comment]
@AradAral Sorry but I don't really understand your question, do you mean always shows green like svelte? This is probably not in line with the volar design.
In any case, if you think the design of the function is unreasonable, please open an issue to make a reasonable suggestion instead of complaining.

**Comment by johnsoncodehk** [comment]
I just found that vscode allow extension setup default config (https://code.visualstudio.com/api/references/contribution-points#contributes.configurationDefaults), this problem should be fixed in next version. Sorry for the confusion!
