### ISSUE TITLE
Renaming (F2 Refactor) within the Vue model throws an error

### ISSUE THREAD

**Issue by Jaeiya** [johnsoncodehk/volar#54]
After the 1.20 update, renaming (F2 Rename Symbol) inside a Vue file causes the following error to occur:
![image](https://user-images.githubusercontent.com/2054218/106835167-b2022f00-664b-11eb-9f99-5388c8fe0949.png)

This bug is limited specifically to inside the Vue file `script` tags. Renaming inside the template view works fine. For some reason it only breaks when renaming inside the `script` tags. Another odd caveat, is if I rename immediately after loading into VSCode, it works just fine, but if I edit anything inside the template or other Vue files, it breaks randomly.

I noticed this is **only** an issue with the 1.20+ versions.

**Comment by johnsoncodehk** [comment]
thanks for the report! This problem is usually due to overlapping renaming ranges, can you show [rename preview](https://code.visualstudio.com/updates/v1_42#_rename-preview) from the error location to me?

0.20 refactored a lot of code but did not have too many feature updates, you can temporarily fall back to 0.19 to avoid this problem.

**Comment by johnsoncodehk** [comment]
should be fixed in 0.20.2, let me know if still not working :)

**Comment by Jaeiya** [comment]
Sorry I didn't get back to you sooner on this; the rename preview actually displayed correctly, which was odd since when you executed it, it just failed.

Anyway, I'll test this out immediately and get back to you 😄

**Comment by Jaeiya** [comment]
It appears to be fixed!! This was bugging me a lot so thanks for the super speedy fix ❤️
