### ISSUE TITLE
incremental parser support

### ISSUE THREAD

**Issue by IWANABETHATGUY** [johnsoncodehk/volar#56]
tree-sitter is a error tolerant and incremental parser, which is blazing fast for editor scenario, i took a glance at our codebase, which has using a lot of Regular Expression and hardcoding parsing, which is  inefficient. I am pretty familiar with tree-sitter , and I am willing to integrate it with our project. However i am not familiar with our project ,  maybe you could write a more detailed infrastructure to me ?

**Comment by IWANABETHATGUY** [comment]
here is the `tree-sitter` homepage: https://tree-sitter.github.io/tree-sitter/
`tree-sitter-vue` : https://ikatyang.github.io/tree-sitter-vue/ you can try here,
![8UWKyACuVU](https://user-images.githubusercontent.com/17974631/106875027-2eab1100-6711-11eb-93ba-3ae042638dae.gif)
1200+ line `vue` file , first parsing only took `6ms`, after that , every keystroke only cost `0.3` ms

**Comment by johnsoncodehk** [comment]
Yes, of course we can consider using it :) Solving performance problems is the purpose of establishing this project.

Quick preview for what volar parser using:

|                         | parser                                                        | for                                            |
| ----------------------- | ------------------------------------------------------------- | ---------------------------------------------- |
| SFC                     | @vue/compiler-sfc -> parse                                    | Virtual documents mapping                      |
| `<template>`            | @vue/compiler-dom -> compile                                  | Virtual template script                        |
| `<template lang="pug">` | @vue/compiler-dom -> compile + **Regex**                      | Virtual template script + html <-> pug mapping |
| `<script>`              | typescript -> createSourceFile -> getStart / End              | Virtual `<script setup>` script                |
| `<script setup>`        | typescript -> createSourceFile -> getStart / End              | Virtual `<script setup>` script                |
| `<style>`               | vscode-css-languageservice -> findDocumentSymbols + **Regex** | Extra css service                              |

There are currently no obvious performance problems with regex, because the usage of regex is very small, and in the case of on-demand calculation, regex will not be calculated if `<template lang="pug">`, `<style>` block is not changed.

But we have performance problems from typescript's `getStart()`, `getStart()` is very expensive, and the diagnosis will be significantly lagging when ref sugar is used extensively in `<script setup>`. Replacing typescript with tree-sitter seems to solve this problem.

The project is still changing rapidly, discussing efficiency in github may be very low, you can find me on discord if you need, my id is `johnsoncodehk#0495`.
