### ISSUE TITLE
Volar ts plugin seems no need to drop the original response

### ISSUE THREAD

**Issue by Kingwl** [johnsoncodehk/volar#654]
We are using some other ts plugin to improve the DX. but it's seems conflicted with volar.

May we keep the original completion or inline complertion for ts file? That seems not affert with vue files.

I’m not 100% sure. So correct me if i'm wrong.

**Comment by johnsoncodehk** [comment]
As far as I understand the working principle of TS plugin, it should be related to the execution order of plugins.

When the TS server executes auto-complete, the TS server will request a new getCompletionsAtPosition function from the volar TS plugin. The original getCompletionsAtPosition is replaced, so other TS plugin behaviors before this will be lost.

Unless volar returns a wrapper function to calculate the new and old getCompletionsAtPosition at the same time, but this requires double the calculation time, and I guess it will cause duplicate results in auto-complete.

I think the correct solution is to control other TS plugins to execute later than volar, so that volar will not affect other TS plugins.
Maybe just sort the plugins option of tsconfig?

**Comment by Kingwl** [comment]
I'm using extensions(both of our plugin and volar plugin) to contribute ts plugin. so there's no way to set the order. Might be a vscode issue i guess?

**Comment by johnsoncodehk** [comment]
@Kingwl does other extensions released TS plugin module to npm?

If so you can install TS plugin to project and add to tsconfig `plugins`, change VSCode TS version to workspace version, and disabled all these TS plugin extensions in vscode, otherwise the same plugins may be loaded repeatedly.

If not, currently no solution as I know, you can open a feature request to vscode for this.

**Comment by Kingwl** [comment]
> If so you can install TS plugin to project and add to tsconfig plugins
Yep, that's what we are doing for now.

But if you have many plugins, you have to add them to package.json and tsconfig.json. It's a little noisy. 
I want to release a extension who has many ts plugins. looks like a `dev toolkit`. And we can easily upgrade any(or all) of them by the extension's update in vscodemarketplace

Anyway, thanks for the response!
