### ISSUE TITLE
Weird error with pug template in volar 0.29.0

### ISSUE THREAD

**Issue by sinbino** [johnsoncodehk/volar#676]
When open the pug template with volar 0.29.0, it reports the incorrect error.
Previous versions (e.g. 0.28.10) do not have this problem.

```
<template lang="pug">
div
  div.foo(v-if="cond")
  
  div.bar(v-else)
</template>
```
In the above code, the following error occurs
```
v-else/v-else-if has no adjacent v-if or v-else-if.vue(30)
```
Remove the blank line between foo and bar, and the error disappears.

```
<template lang="pug">
Foo
  template(v-slot:header)
    div FOO

  template(v-slot)
    div Bar
</template>
```
In the above code, the following error occurs
```
Extraneous children found when component already has explicitly named default slot. These children will be ignored.
```
Remove the blank lines in the two template tags, and the error disappears.

I created a repository to reproduce the problem.
https://github.com/sinbino/issue-volar-0.29.0

**Comment by Shinigami92** [comment]
Are you sure (cleaned node_modules and so on) that it works with `0.28.10`? Otherwise I would assume that it could have something to do with the fix for me: https://github.com/johnsoncodehk/volar/issues/636

I will try to reproduce this in my company project in some minutes/hours and look if I also got affected by this.

**Comment by Shinigami92** [comment]
@johnsoncodehk I can confirm this 👍
