### ISSUE TITLE
Circular references between Vue 3 components cannot be resolved

### ISSUE THREAD

**Issue by benruehl** [johnsoncodehk/volar#677]
Opening a new issue because I cannot reopen #644.
I added a comment but it seems it got lost because the issue was already closed.
Sorry if this is not the right way to address this.

To summarize the original issue:
Circular references between Vue 3 components implemented via `script setup` lead to errors in the components' templates. The app builds and runs totally fine though. A different IDE (Webstorm) has no issue with the situation as well, so it seems to be related to Volar.

**Comment by johnsoncodehk** [comment]
As I said in #644, this is a limitation (or design) of TS, and TS cannot resolve circular type.

This is the minimal reproduction of TS code.

```ts
// foo.ts
import { defineComponent } from 'vue';

const Foo = defineComponent({ setup() { return { Bar } } }); // 'Foo' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
const Bar = defineComponent({ setup() { return { Foo } } }); // 'Bar' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
```

> If it would be an issue with typescript why does the typescript compiler run successfully then?

typescript compiler (I think you are talking `tsc`) build success because it's just ignore *.vue files, type errors in *.vue is not affect to `tsc`.

> Just to remember: The app builds and runs perfectly fine. There are no runtime or compile time errors.

This is not how TS works. You should infer that the runtime is working good by the TS no errors, not by inferring that the TS no errors by because runtime working good.

> In addition, we opened the project in Webstorm which does not have any issues with it either.

I would say that this is a bug in Webstorm, and it should have an error.

---

This is really not a Volar issue. For TS issues, please discuss on the [Vue official TS channel](https://discord.com/channels/325477692906536972/331999220125138944), thanks.
