### ISSUE TITLE
Is it possible to build a vue3 project typecheck tool based on Volar?

### ISSUE THREAD

**Issue by oliverzy** [johnsoncodehk/volar#71]
Hi Author,

Volar is the really awesome tool for Vue based project.
Currently it's not possible to typecheck .vue files via tsc.
Typecheck only in vscode is not enough for big project.
I wonder if it's possible to build a typecheck tool based on Volar?
Is it a good idea or not?

Please advice.

**Comment by johnsoncodehk** [comment]
yes I will publish a typescript plugin for tsc in future, but this work is currently at a low priority.

**Comment by oliverzy** [comment]
OK, the idea is creating CLI tool based Volar to do typecheck for Vue SFC, right?
Really looking forward to.

**Comment by yyx990803** [comment]
@johnsoncodehk I would love to see this happen! Is a TS plugin going to be able to cover the use case?

I know Vetur has [vti](https://vuejs.github.io/vetur/guide/vti.html#why) which emits Vetur's diagnostics from the command line, but is *.vue files only.

It'd be nice to either:

- Emit both TS and Vue diagnostics via `tsc` + a TS plugin
- If the above is difficult, maybe something like vti, but wraps `tsc`?

**Comment by johnsoncodehk** [comment]
@yyx990803 like you said, I will try to proxy tsc command. if it's impossible, I will provide volar command tool like vti.

I will implement this feature first because this is sponsor rewards. :)

**Comment by oliverzy** [comment]
Excellent, this will close the gap in the Vue TS tooling ecosystem

**Comment by johnsoncodehk** [comment]
@yyx990803 we need to support run dev server with `tsc` watch mode?

intuitively the command is `tsc --watch && vite`, but it's not working, see: https://stackoverflow.com/questions/38276862/is-there-a-way-to-use-npm-scripts-to-run-tsc-watch-nodemon-watch

there solution is use [tsc-watch](https://github.com/gilamran/tsc-watch), but the problem is that will lose `vite` incremental update. so the problem is how to make `tsc` incremental update and `vite` incremental update work together.

or we only need to support type-checking on build not dev server?

**Comment by johnsoncodehk** [comment]
check it: https://www.npmjs.com/package/vue-tsc

**Comment by johnsoncodehk** [comment]
> @yyx990803 like you said, I will try to proxy tsc command. if it's impossible, I will provide volar command line tool like vti.
> 
> I will implement this feature first because this is sponsor reward. :)

Someone quote this comment and said some very rude words, I has clearly pointed out sponsor's requests have high priority on [Sponsor](https://github.com/sponsors/johnsoncodehk) page.

Sponsorship is the only income of this OSS project, and I tried my best to fulfill my promise. Otherwise I don't have motivation to maintain this project. So don't do that.

**Comment by LiJiahaoCoder** [comment]
> > @yyx990803 like you said, I will try to proxy tsc command. if it's impossible, I will provide volar command line tool like vti.
> > I will implement this feature first because this is sponsor reward. :)
> 
> Someone quote this comment and said some very rude words, I has clearly pointed out sponsor's requests have high priority on [Sponsor](https://github.com/sponsors/johnsoncodehk) page.
> 
> Sponsorship is the only income of this OSS project, and I tried my best to fulfill my promise. Otherwise I don't have motivation to maintain this project. So don't do that.

文章内容并无恶意，本想开个玩笑，未曾想弄巧成拙，对您造成的困扰深表歉意。

您的行动力及效率之高我十分钦佩，我尊重每位开发者和开源人，他们可敬可爱，我也梦想成为一位开源人！

相关文章已删除，并在相关平台发表声明表达歉意，十分抱歉！
