### ISSUE TITLE
Disable volar type checking for component prop evaluation

### ISSUE THREAD

**Issue by Evertvdw** [johnsoncodehk/volar#735]
Hi there!

I'm using a library which has defined props for its components. Now I want to use those components in a certain predefined way so I created a wrapper around those components, so I can set some props by default.

For example I have this wrapper  defined:
```vue
<template>
	<q-checkbox dense class="mett-checkbox" color="primary" :class="{ label: label }" :label="label">
		<slot />
	</q-checkbox>
</template>

<script setup lang="ts">
defineProps<{
	label?: string;
}>();
</script>
```

I want to use this component like:
```vue
<mett-checkbox v-model="something" size="sm">
```

This works because attributes are automatically passed on to the root element. The library component in question has a required prop, namely `modelValue` but I can't define that inside the wrapper.  However the props type validation is complaining in the wrapper that this required prop is not set:
![image](https://user-images.githubusercontent.com/5757159/143411761-9f2f63fd-b8b1-470e-bc2e-9355ba26f733.png)

Is there a way around this, by for instance disabling Volar type checking for this line? I was trying to disable type checking for this component, but this did not work:
```vue
<template>
        <!-- eslint-disable-next-line --> or <!-- @ts-ignore -->
	<q-checkbox dense class="mett-checkbox" color="primary" :class="{ label: label }" :label="label">
		<slot />
	</q-checkbox>
</template>
```

Thanks in advance!

**Comment by sethidden** [comment]
>but I can't define that inside the wrapper.

Why not?
```diff
<template>
	<q-checkbox 
+         :modelValue="modelValue" @update:modelValue="$emit('update:modelValue', $event)" 
          dense
          class="mett-checkbox"
          color="primary"
          :class="{ label: label }"
          :label="label">
		<slot />
	</q-checkbox>
</template>

<script setup lang="ts">
defineProps<{
	label?: string;
+        modelValue: boolean;
}>();
</script>
```
You just need to create an intermediary layer between the top-level v-model, your wrapper (in between) and the q-checkbox and "re-emit/bubble up" the v-model event. The events and props to q-checkbox may be different than I provided. Please open up Vue devtools in your browser to check which props and events you should watch for if that's the case.

https://v3.vuejs.org/guide/component-basics.html#using-v-model-on-components

Obviously something like this wouldn't work:
```
<q-checkbox v-model="modelValue">
```
since that would just try to assign to modelValue directly using the `=` operator. (

**Comment by johnsoncodehk** [comment]
@sethidden's answer is correct, just to make some additions.

At present, volar does not consider add new syntax to ignore errors, because I think this will cause more confusion to the community than benefits, and unless the syntax becomes a vue standard, it is specific to volar and not applicable to webstorm.

We discussed similar issues in discord, and you also can do this.
```html
<template>
	<q-checkbox v-model="modelValueProxy">
		<slot />
	</q-checkbox>
</template>

<script setup lang="ts">
import { defineProps, defineEmits, computed } from 'vue';

const props = defineProps<{ modelValue: unknown }>();
const emit = defineEmits<{ (e: 'update:modelValue', value: unknown): void }>();

const modelValueProxy = computed({
  get: () => props.modelValue,
  set: value => emit("update:modelValue", value),
});
</script>
```
