### ISSUE TITLE
Rewrite `vscode-vue-languageservice`

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#763]
The core code is written in the process of exploration, it is unmaintainable by others currently, planned to be rewritten in February 2022.

**Comment by IWANABETHATGUY** [comment]
And also we need to rethink the core implementation due to the poor performance in large project, for example  https://github.com/jekip/naive-ui-admin/tree/main. in my MacBook Pro (16-inch, 2019) 2.6 GHz six core Intel Core i7, code completion took about 1.5s every key stroke
![image](https://user-images.githubusercontent.com/17974631/145163406-c86fcb7c-1671-4f47-9031-2935c25eef8d.png)
![image](https://user-images.githubusercontent.com/17974631/145163551-3cf2be88-416b-45c0-9504-c856167d6e56.png)

**Comment by johnsoncodehk** [comment]
@IWANABETHATGUY will check this repo, thanks.

**Comment by johnsoncodehk** [comment]
@IWANABETHATGUY please track #808.
