### ISSUE TITLE
Cannot access ambient const enums when the '--isolatedModules' flag is provided.

### ISSUE THREAD

**Issue by mesqueeb** [johnsoncodehk/volar#797]
In some cases when I run 
`vue-tsc --declaration --emitDeclarationOnly` to generate the typescript types for my component library, I get this error:

```
../../node_modules/@vue/runtime-core/dist/runtime-core.d.ts:1215:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

1215     [BooleanFlags.shouldCast]?: boolean;
          ~~~~~~~~~~~~
```
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/3253920/146479603-ea65bf35-6130-41b8-825e-5d62d29892f7.png">

AFAIK I can't really change this because it's something that Vue does internally...

Is the only solution to _not_ use `"isolatedModules": true,` in tsconfig for my component library?

when I remove this it works, but I was hoping there is a way I can keep it.

**Comment by LinusBorg** [comment]
The solution would be to set `skipLibCheck: true` in tsconfig. 

Coincidentally, that's what `tsc init` sets by default now since the last TS release, as there seem to be too many scenarios where type conflicts in packages types are incompatible with one another or with the project they are used in. This setting also increases build perf as TS doesn't check *all* of the types of every lib used, just the ones you actually import or implicitly reference by using some API.

Either way, this is a TS problem, not a Volar problem.

**Comment by mesqueeb** [comment]
@LinusBorg how interesting! 
Thank you so much for the clarification. Yet again, I learned something new from you : )
