### ISSUE TITLE
Feature Request: support generic emits

### ISSUE THREAD

**Issue by xiaoxiangmoe** [johnsoncodehk/volar#877]
```vue
<script setup lang="ts">
declare const Bar: new <T>(props: { value: T }) => {
  $props: typeof props;
  $emit: {
    (event: "update:value", e: T): void;
  };
};
const console = window.console;
</script>
<template>
  <div id="app">
    <Bar :value="1" @update:value="console.log($event)" />
  </div>
</template>
```

The type of `$event` should be `number`

**Comment by johnsoncodehk** [comment]
Thanks for the report!

**Comment by Fuzzyma** [comment]
@johnsoncodehk if this works, does it work with generic props + spot props as well? And if so, how would I write this?

**Comment by xiaoxiangmoe** [comment]
In vue 2:
```vue
<script lang="ts">
import { VNode } from 'vue';

declare const Bar: new <T>(props: { readonly value: T; readonly 'onUpdate:value'?: (value: T) => void }) => {
    $props: typeof props;
    $scopedSlots: {
        default?: ({ foo }: { readonly foo: T }) => VNode[] | undefined;
    };
};
const console = window.console;
</script>
<script setup lang="ts"></script>
<template>
    <div id="app">
        <Bar :value="1" @update:value="console.log($event)">
            <template #default="{ foo }">
                {{ foo + 1 }}
            </template>
        </Bar>
    </div>
</template>
```

In vue 3:

change $scopedSlots to $slots

**Comment by xiaoxiangmoe** [comment]
@Evertt Sorry, I don't know. Maybe you should create a issue for it.

**Comment by Evertt** [comment]
@xiaoxiangmoe okay thank you. For now I found an acceptable solution, which looks like this:

```ts
import { VNode } from 'vue'

const column_options = [
  "checked",
  "index",
  "filename",
  "name",
  "quantity",
  "material",
  "thickness",
  "process",
  "operations",
  "reference",
  "certificates",
  "is_valid",
  "price",
  "total",
  "actions"
] as const

type A<T> = {
  [key in typeof column_options[number]]: ({ column, index, row } :{
    readonly column: key
    readonly index: number
    readonly row: T
  }) => VNode[] | undefined
}

type B<T> = {
  [key in string]: ({ column, index, row } :{
    readonly column: key
    readonly index: number
    readonly row: T
  }) => VNode[] | undefined
}

declare const VClientTable: new <T>(props: { readonly data: T[] }) => {
  $props: typeof props;
  $slots: A<T> & B<T>
}
```

The result is that any slot whose name is one of the `column_options`, I will get the exact type that I want, namely this:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/1267282/161463458-981aa297-5fe2-4c61-bce0-a9d88f0ed82a.png">

And any slot whose name is not one of the `column_options`, I will get nearly the exact type I want:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/1267282/161463601-6c84f73a-b271-4488-aca5-b48cd19b4373.png">

Like it would've been nice if `column` had still been `"quantityyyyy"`, but this is already miles better than what I got before. Because when I asked you the question a few days ago, `data` was just always `any`.

But anyhow, I actually wanted to ask you one more question. I hope I'm not asking too much.

In your example, and also in my code, you are giving the `Bar` component its type definition from within another component; from within the component that's *using* the `Bar` component. Do you know if it's possible to give the `Bar` component its type definition from within the `Bar` component itself?

I know it's possible to define an `export type` inside `Bar.vue`, but then in every component where you want to use `Bar`, you'd need to do something like this:

```ts
import BarComp, { BarType } from "./Bar.vue"
const Bar = BarComp as BarType<number>
```

I'm hoping there's a more elegant solution, where I can just `import Bar from "./Bar.vue"` and by simply using it like your example: `<Bar :value="1" @update:value="console.log($event)" />`, the type of `$event` is implied through the generics.

Do you know a way to do that from within `Bar.vue`?
