### ISSUE TITLE
volar 0.31.0 cannot resolve imports from vue file.

### ISSUE THREAD

**Issue by Ubugeeei** [johnsoncodehk/volar#886]
![スクリーンショット 2022-01-22 15 28 31](https://user-images.githubusercontent.com/71201308/150627793-ddec7dc8-9f1e-483b-95a5-5a33e5d1e28b.png)

v0.30.6 is fine.

**Comment by johnsoncodehk** [comment]
I guess you are export that in `<script setup>`. After 0.31 script setup code scope is more strict, you need to move your export code from `<script setup>` to `<script>`.

**Comment by Ubugeeei** [comment]
@johnsoncodehk 
Oh !! Thanks ! It working!

**Comment by johnsoncodehk** [comment]
After discussing with the team, the latest version should hoist type export statements on the top in `<script setup>`.

For example:

```html
<script setup lang="ts">
import { ref } from 'vue';

export type A = {}; // this is support

const count = ref(0);

export type B = {}; // this is not support, type export statements on the top
</script>
```

**Comment by Ubugeeei** [comment]
awesome !

**Comment by sinbino** [comment]
@johnsoncodehk
Can I see a discussion in public about how this change was made?

**Comment by johnsoncodehk** [comment]
@sinbino We didn't discuss this publicly, and volar's limited support for export in script setup is just to align with the vue compiler's implementation to a certain extent, because supporting export in script setup would actually cause some trouble for volar.

Please note this is really just my personal advice. I think it is semantically clearer to always define export in `<script>` rather than in `<script setup>` and also avoid unnecessary misdirection of code scope. I hope the community to use export in `<script>` whenever possible and avoid discussing how export is used in `<script setup>`.
