### ISSUE TITLE
Named v-slots fail

### ISSUE THREAD

**Issue by srav001** [johnsoncodehk/volar#893]
Hi, this is my first issue. Please do let me know if anything is missing.
##
Error:

`error TS7053: Element implicitly has an 'any' type because expression of type '"default-view-body"' can't be used to index type '{} | {}'.`

* Whenever using `v-slot` or `#` shorthand on component `template` tag.

https://github.com/srav001/vue-ionic-template

Issue can be found in this repo. In the file Home.vue a named slot is being used from BaseView.vue.  `npm run dev` works, but building it fails with above mentioned error.  

> I found a similar issue in the older repo but it was never followed up by the issuer - https://github.com/johnsoncodehk/vue-tsc/issues/82.

**Comment by johnsoncodehk** [comment]
You should change `"core/*": ["/core/*"],` to `"core/*": ["core/*"],` in tsconfig.

**Comment by srav001** [comment]
Oh I see. Thanks a lot for the fix. Didn't know that would create such an issue.

**Comment by johnsoncodehk** [comment]
I also recommend you to remove shims-vue.d.ts, it causes false positives for invalid import path.

**Comment by srav001** [comment]
Oh okay, will do. Thank you.

**Comment by sixpounder** [comment]
I would like to add my own experience to this: vue-tsc brings up this exact error if I use webpack resolve aliases into a vite.config.ts file (took me an afternoon to realize the cause).

Not working example:

```typescript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
const path = require('path')

// https://vitejs.dev/config/
export default defineConfig({
  resolve:{
     alias:{
       '@' : path.resolve(__dirname, './src')
     },
  },
  plugins: [vue()]
})
```

With these components:

```vue
<template>
  <div role="presentation" class="layout-wrap">
    <div class="left-wrapper">
      <slot name="left"></slot>
    </div>
    <div class="right-wrapper break-words bg-slate-100 dark:bg-gray-800">
      <slot name="right"></slot>
    </div>
  </div>
</template>

<script lang="ts">

import { defineComponent } from 'vue';

export default defineComponent({
  name: 'MainLayout'
})
</script>
```

```vue
<template>
  <main class="md:container mx-4 md:mx-auto">
    <MainLayout>
      <template v-slot:left>
        Whatever
      </template>
      <template v-slot:right>
        Whatever
      </template>
    </MainLayout>
  </main>
</template>

<script lang="ts">
import MainLayout from '@/layouts/MainLayout.vue'

export default defineComponent({
  components: {
    MainLayout
  }
})
```

This yields

`error TS7053: Element implicitly has an 'any' type because expression of type '"left"' can't be used to index type '{} | {}'.`

`error TS7053: Element implicitly has an 'any' type because expression of type '"right"' can't be used to index type '{} | {}'.`

Once all references to the @ alias and the alias configuration reported above are removed the error disappears.

**Comment by ryannmedina** [comment]
@sixpounder your solution worked for me as well. Thank you! This seems so unrelated, any idea on why it's a problem?

**Comment by sixpounder** [comment]
> @sixpounder your solution worked for me as well. Thank you! This seems so unrelated, any idea on why it's a problem?

I honestly have no idea because I didn't nosedive into volar code to further investigate this issue, but I can make an educated guess given the errors: _maybe_ volar doesnt correctly type templates collections and sees them as a `{}` type, when something like `Record<string, unknown>` or better should be used? I repeat, just a guess.

**Comment by rfox12** [comment]
This is a Volar issue and should not be closed...

**Comment by joelxr** [comment]
This is still failing for me for some reason.
![image](https://user-images.githubusercontent.com/3206427/211089795-c774eaf9-37f6-4e00-bb14-34eb4520dbb1.png)

**Comment by sixpounder** [comment]
> This is still failing for me for some reason. ![image](https://user-images.githubusercontent.com/3206427/211089795-c774eaf9-37f6-4e00-bb14-34eb4520dbb1.png)

Have you tried removing the @ aliases from your vite config?
