### ISSUE TITLE
Required props check not working when importing props object from another file

### ISSUE THREAD

**Issue by theoephraim** [johnsoncodehk/volar#933]
(UPDATED - thanks @sethidden)

It appears type checks that ensure a required prop is set when using a component is not working when

- component is defined with script setup
- props are set via object syntax (not type syntax)
- object is imported from another file

For example

props defined in another file props.ts
```typescript
export const props = {
  requiredProp: { type: String, required: true },
}
```

and defining the component
```vue
<script lang="ts" setup>
import { props } from './props.ts';
defineProps(props);
</script>
```

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1158956/152700027-c5eb1814-25dd-4970-ad59-4f848b30e6d6.png">

repro here - https://github.com/theoephraim/vue-ts-props-bugs/blob/main/src/required-prop-tests/Test.vue#L29

**Comment by sethidden** [comment]
If I use a regular inline object as props definition rather than an importing it from a file it's working OK. Guess vue-tsc doesn't snoop for props definitions throughout imports?

![image](https://user-images.githubusercontent.com/5359825/152697026-cd123aa7-3ce7-468f-92dd-8f5d60903706.png)
![image](https://user-images.githubusercontent.com/5359825/152697070-8b6469d0-267a-4349-a50c-693434ab1014.png)

**Comment by theoephraim** [comment]
Oh interesting - I moved it to simplify the examples. I do use this pattern sometimes though to extract common props so ideally it should still work. I’ll add more cases to the repro.
